"""Framework-neutral model format adapter contracts."""

from modelsurgeon.adapters.base import (
    AdapterCapability,
    AdapterIdentity,
    ComponentDescriptor,
    ModelAdapter,
    ModelFormat,
    ModelSession,
    ModelSource,
    MutationSupport,
    OpenOptions,
    TensorChunk,
    TensorDescriptor,
    UnsupportedCapabilityError,
    require_capability,
)
from modelsurgeon.adapters.competitor import (
    COMPETITOR_ADAPTER_SCHEMA_VERSION,
    CompetitorAdapterError,
    CompetitorBudget,
    CompetitorIdentity,
    CompetitorOutcome,
    CompetitorProvenance,
    CompetitorRunResult,
    CompetitorTelemetry,
    SubprocessCompetitorAdapter,
)
from modelsurgeon.adapters.family import (
    ArchitectureDetectionError,
    ArchitectureEvidence,
    ConflictingArchitectureError,
    FamilySelection,
    ModelFamily,
    UnknownArchitectureError,
    detect_model_family,
)

__all__ = [
    "COMPETITOR_ADAPTER_SCHEMA_VERSION",
    "AdapterCapability",
    "AdapterIdentity",
    "ArchitectureDetectionError",
    "ArchitectureEvidence",
    "CompetitorAdapterError",
    "CompetitorBudget",
    "CompetitorIdentity",
    "CompetitorOutcome",
    "CompetitorProvenance",
    "CompetitorRunResult",
    "CompetitorTelemetry",
    "ComponentDescriptor",
    "ConflictingArchitectureError",
    "FamilySelection",
    "ModelAdapter",
    "ModelFamily",
    "ModelFormat",
    "ModelSession",
    "ModelSource",
    "MutationSupport",
    "OpenOptions",
    "SubprocessCompetitorAdapter",
    "TensorChunk",
    "TensorDescriptor",
    "UnknownArchitectureError",
    "UnsupportedCapabilityError",
    "detect_model_family",
    "require_capability",
]

