"""Versioned framework-neutral model feature records and extractors."""

from modelsurgeon.features.activation import ActivationBatch, ActivationSummaryCollector
from modelsurgeon.features.activation_covariance import (
    ACTIVATION_COVARIANCE_EXTRACTOR_VERSION,
    ActivationCovarianceCollector,
    ActivationCovarianceConfig,
    ActivationCovarianceError,
    ActivationCovarianceSummary,
    CovarianceAccuracyReport,
    evaluate_covariance_accuracy,
)
from modelsurgeon.features.channel_activation import (
    ChannelActivationCollector,
    ChannelActivationConfig,
    ChannelActivationFeature,
    ChannelActivationSummary,
)
from modelsurgeon.features.cosine_similarity import (
    COSINE_SIMILARITY_EXTRACTOR_VERSION,
    CosineCandidate,
    CosineCandidateMode,
    CosineSimilarity,
    CosineSimilarityConfig,
    CosineSimilarityError,
    CosineVector,
    CosineVectorKind,
    cosine_similarity_for_candidate,
    extract_pairwise_cosine_similarities,
    generate_cosine_candidates,
)
from modelsurgeon.features.gradient_features import (
    GRADIENT_FEATURE_EXTRACTOR_VERSION,
    GradientFeatureError,
    GradientFeatureOutcome,
    GradientFeatures,
    extract_gradient_features,
)
from modelsurgeon.features.neuron_correlation import (
    NEURON_CORRELATION_EXTRACTOR_VERSION,
    ChannelRedundancyInput,
    DuplicateChannelFeature,
    NeuronCorrelationConfig,
    NeuronCorrelationError,
    rank_duplicate_channels,
)
from modelsurgeon.features.schema import (
    FEATURE_SCHEMA_VERSION,
    ErrorProvenance,
    FeatureKind,
    FeatureRecord,
    FeatureSampleContext,
    PrecisionProvenance,
    PrecisionSource,
)
from modelsurgeon.features.spectral_exact import (
    EXACT_SPECTRAL_EXTRACTOR_VERSION,
    ExactSpectralConfig,
    ExactSpectralError,
    ExactSpectralFeatures,
    ExactSpectralOutcome,
    extract_exact_spectral_features,
)
from modelsurgeon.features.spectral_randomized import (
    RANDOMIZED_SPECTRAL_ALGORITHM,
    RANDOMIZED_SPECTRAL_EXTRACTOR_VERSION,
    RandomizedSpectralConfig,
    RandomizedSpectralError,
    RandomizedSpectralFeatures,
    RandomizedSpectralOutcome,
    RandomizedWorkspacePlan,
    extract_randomized_spectral_features,
    plan_randomized_spectral_workspace,
)
from modelsurgeon.features.weight_distribution import (
    WEIGHT_DISTRIBUTION_EXTRACTOR_VERSION,
    WeightDistribution,
    WeightDistributionConfig,
    WeightDistributionError,
    extract_weight_distribution,
)
from modelsurgeon.features.weight_statistics import (
    WEIGHT_STATISTICS_EXTRACTOR_VERSION,
    WeightStatistics,
    WeightStatisticsError,
    WeightTensor,
    extract_weight_statistics,
)

__all__ = [
    "ACTIVATION_COVARIANCE_EXTRACTOR_VERSION",
    "COSINE_SIMILARITY_EXTRACTOR_VERSION",
    "EXACT_SPECTRAL_EXTRACTOR_VERSION",
    "FEATURE_SCHEMA_VERSION",
    "GRADIENT_FEATURE_EXTRACTOR_VERSION",
    "NEURON_CORRELATION_EXTRACTOR_VERSION",
    "RANDOMIZED_SPECTRAL_ALGORITHM",
    "RANDOMIZED_SPECTRAL_EXTRACTOR_VERSION",
    "WEIGHT_DISTRIBUTION_EXTRACTOR_VERSION",
    "WEIGHT_STATISTICS_EXTRACTOR_VERSION",
    "ActivationBatch",
    "ActivationCovarianceCollector",
    "ActivationCovarianceConfig",
    "ActivationCovarianceError",
    "ActivationCovarianceSummary",
    "ActivationSummaryCollector",
    "ChannelActivationCollector",
    "ChannelActivationConfig",
    "ChannelActivationFeature",
    "ChannelActivationSummary",
    "ChannelRedundancyInput",
    "CosineCandidate",
    "CosineCandidateMode",
    "CosineSimilarity",
    "CosineSimilarityConfig",
    "CosineSimilarityError",
    "CosineVector",
    "CosineVectorKind",
    "CovarianceAccuracyReport",
    "DuplicateChannelFeature",
    "ErrorProvenance",
    "ExactSpectralConfig",
    "ExactSpectralError",
    "ExactSpectralFeatures",
    "ExactSpectralOutcome",
    "FeatureKind",
    "FeatureRecord",
    "FeatureSampleContext",
    "GradientFeatureError",
    "GradientFeatureOutcome",
    "GradientFeatures",
    "NeuronCorrelationConfig",
    "NeuronCorrelationError",
    "PrecisionProvenance",
    "PrecisionSource",
    "RandomizedSpectralConfig",
    "RandomizedSpectralError",
    "RandomizedSpectralFeatures",
    "RandomizedSpectralOutcome",
    "RandomizedWorkspacePlan",
    "WeightDistribution",
    "WeightDistributionConfig",
    "WeightDistributionError",
    "WeightStatistics",
    "WeightStatisticsError",
    "WeightTensor",
    "cosine_similarity_for_candidate",
    "evaluate_covariance_accuracy",
    "extract_exact_spectral_features",
    "extract_gradient_features",
    "extract_pairwise_cosine_similarities",
    "extract_randomized_spectral_features",
    "extract_weight_distribution",
    "extract_weight_statistics",
    "generate_cosine_candidates",
    "plan_randomized_spectral_workspace",
    "rank_duplicate_channels",
]
