"""Transactional model mutation APIs."""

from modelsurgeon.surgery.contracts import (
    MUTATION_SCHEMA_VERSION,
    MutationCompatibility,
    MutationContractError,
    MutationDelta,
    MutationKind,
    MutationPlan,
    MutationPrecondition,
    MutationRequest,
    MutationTransaction,
    TransactionalMutation,
    TransactionState,
    require_safe_transaction,
)
from modelsurgeon.surgery.physical_plan import (
    PHYSICAL_MUTATION_PLAN_SCHEMA_VERSION,
    AxisRemoval,
    PhysicalMetadataUpdate,
    PhysicalMutationPlan,
    PhysicalPlanError,
    PhysicalTensorDescriptor,
    PhysicalTensorEdit,
    TensorAxisTransform,
    TensorEditIntent,
    compile_physical_mutation_plan,
)
from modelsurgeon.surgery.serialization import (
    MUTATION_RECORD_SCHEMA_VERSION,
    REDACTED_LOCAL_PATH,
    MutationIdentityMapping,
    MutationOutcome,
    MutationOutcomeStatus,
    MutationProvenance,
    MutationRecordError,
    MutationRunRecord,
)
from modelsurgeon.surgery.target_resolution import (
    MutationTargetResolutionError,
    ResolvedMutationTarget,
    ResolvedMutationTargets,
    resolve_mutation_targets,
)

__all__ = [
    "MUTATION_RECORD_SCHEMA_VERSION",
    "MUTATION_SCHEMA_VERSION",
    "PHYSICAL_MUTATION_PLAN_SCHEMA_VERSION",
    "REDACTED_LOCAL_PATH",
    "AxisRemoval",
    "MutationCompatibility",
    "MutationContractError",
    "MutationDelta",
    "MutationIdentityMapping",
    "MutationKind",
    "MutationOutcome",
    "MutationOutcomeStatus",
    "MutationPlan",
    "MutationPrecondition",
    "MutationProvenance",
    "MutationRecordError",
    "MutationRequest",
    "MutationRunRecord",
    "MutationTargetResolutionError",
    "MutationTransaction",
    "PhysicalMetadataUpdate",
    "PhysicalMutationPlan",
    "PhysicalPlanError",
    "PhysicalTensorDescriptor",
    "PhysicalTensorEdit",
    "ResolvedMutationTarget",
    "ResolvedMutationTargets",
    "TensorAxisTransform",
    "TensorEditIntent",
    "TransactionState",
    "TransactionalMutation",
    "compile_physical_mutation_plan",
    "require_safe_transaction",
    "resolve_mutation_targets",
]
