"""Canonical finite v1.0 issue catalog used to configure GitHub.

Keep entries topologically ordered: dependencies must refer to earlier keys. The GitHub
bootstrapper validates this invariant and renders the complete issue template.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class IssueSpec:
    key: str
    title: str
    milestone: str
    phase: str
    priority: str
    kind: str
    effort: str
    risk: str
    area: str
    dependencies: tuple[str, ...]
    scope: str
    acceptance: tuple[str, ...]
    tests: tuple[str, ...]


MILESTONES = (
    ("v0.1 — Foundation", "Repository, contracts, adapters, identities, discovery and graph."),
    ("v0.2 — Instrumentation", "Calibration and bounded, versioned feature extraction."),
    ("v0.3 — Mutation Lab", "Transactional masking, rollback and tiered cheap evaluation."),
    ("v0.4 — Experiment Dataset", "Resumable campaigns and leakage-safe persisted examples."),
    ("v0.5 — First Surgeon", "Heuristic and classical learned prediction baselines."),
    ("v0.6 — Active Surgeon", "Uncertainty-aware experiment selection and retraining."),
    ("v0.7 — Structural and Native GGUF Surgery", "Physical HF and out-of-core quantized GGUF surgery."),
    ("v0.8 — Cross-Model Generalization", "Held-out family, scale and quantization evaluation."),
    ("v0.9 — Automated Optimization", "Constrained iterative search and repair."),
    ("v1.0 — ModelSurgeon", "Stable, reproducible, documented end-to-end release."),
)

PHASES = (
    "Foundation", "Model Introspection", "Instrumentation", "Feature Extraction",
    "Mutation Engine", "Evaluation", "Experiment Dataset", "Baseline Surgeon",
    "Active Learning", "Search", "Structural Surgery", "Generalization",
    "Explainability", "Optimization", "Release",
)


def i(
    key: str,
    title: str,
    milestone: str,
    phase: str,
    priority: str,
    kind: str,
    effort: str,
    risk: str,
    area: str,
    dependencies: tuple[str, ...],
    scope: str,
    *acceptance: str,
    tests: tuple[str, ...] = (),
) -> IssueSpec:
    if not tests:
        tests = (f"Add focused automated tests for {title.lower()}.",)
    return IssueSpec(
        key, title, milestone, phase, priority, kind, effort, risk, area,
        dependencies, scope, tuple(acceptance), tests,
    )


ISSUES: list[IssueSpec] = [
    # v0.1 — Foundation
    i("repo-quality", "Establish repository quality and safety baseline", "v0.1 — Foundation", "Foundation", "P0", "Infrastructure", "S", "Low", "ci", (),
      "Create licensing, contribution, security, templates, dependency updates and checkpoint exclusions.",
      "Apache-2.0, contribution and security policies are present.", "Model weights and experiment artifacts are ignored.",
      tests=("Validate required repository files and ignore patterns in CI.",)),
    i("config-schema", "Implement validated hierarchical configuration schema", "v0.1 — Foundation", "Foundation", "P0", "Feature", "M", "Low", "experiments", ("repo-quality",),
      "Define model, calibration, feature, objective, hardware and safety configuration sections with environment overrides.",
      "Invalid limits and unknown keys are rejected.", "Safe defaults disable overwrites and remote code.", "Canonical serialization is deterministic."),
    i("config-files", "Load and merge reproducible YAML and TOML configuration", "v0.1 — Foundation", "Foundation", "P1", "Feature", "M", "Low", "experiments", ("config-schema",),
      "Load YAML/TOML, merge explicit CLI overrides and expose the canonical resolved document.",
      "Precedence is defaults, file, environment, then CLI.", "Resolved config can be emitted without secrets."),
    i("logging", "Add structured logging with run context", "v0.1 — Foundation", "Foundation", "P1", "Infrastructure", "S", "Low", "experiments", ("repo-quality",),
      "Configure human and JSON logs carrying run, model and component context.",
      "Library import does not configure global logging.", "CLI logs can switch between human and JSON output."),
    i("hardware-inventory", "Collect CPU GPU RAM disk and software inventory", "v0.1 — Foundation", "Foundation", "P1", "Feature", "M", "Low", "experiments", ("config-schema",),
      "Collect reproducibility and scheduling metadata without requiring CUDA.",
      "CPU-only hosts return a valid record.", "CUDA, driver, PyTorch, CPU, RAM, OS and free disk are recorded when available."),
    i("component-id-spec", "Specify canonical component identity grammar", "v0.1 — Foundation", "Model Introspection", "P0", "Documentation", "S", "Low", "graph", (),
      "Document typed paths, escaping, roots, component kinds, sets and post-surgery remapping.",
      "Examples cover layers, heads, channels, projections, embeddings and experts.", "Invalid and ambiguous forms have explicit behavior."),
    i("component-id", "Implement immutable stable component identifiers", "v0.1 — Foundation", "Model Introspection", "P0", "Feature", "M", "Low", "graph", ("component-id-spec",),
      "Implement parse, format, equality, ordering, parent/child and JSON conversion.",
      "Round trips are canonical.", "Negative or malformed segments fail with actionable errors.", "IDs are hashable and immutable."),
    i("adapter-contract", "Define model and architecture adapter capability contracts", "v0.1 — Foundation", "Model Introspection", "P0", "Feature", "M", "Medium", "adapters", ("component-id-spec",),
      "Define loading, discovery, tensor access, identity mapping, mutation capability and safe-failure contracts.",
      "Adapters advertise capabilities and unsupported operations explicitly.", "The contract does not expose framework-specific objects in persisted records."),
    i("hf-loader", "Implement safe Hugging Face causal LM loader", "v0.1 — Foundation", "Model Introspection", "P0", "Feature", "M", "Medium", "adapters", ("config-schema", "adapter-contract"),
      "Load local or Hub causal LMs with pinned revisions, dtype and device-map controls.",
      "Remote code is disabled by default.", "CPU loading works.", "Resolved revision and loader options are returned as provenance."),
    i("safetensors-index", "Inspect safetensors shards and tensor metadata lazily", "v0.1 — Foundation", "Model Introspection", "P1", "Feature", "M", "Low", "adapters", ("adapter-contract",),
      "Read single and sharded safetensors indexes without materializing tensor payloads.",
      "Names, shapes, dtypes, shards and byte sizes are reported.", "Missing shards and malformed indexes fail safely."),
    i("family-detection", "Detect supported architecture families without guessing", "v0.1 — Foundation", "Model Introspection", "P0", "Feature", "M", "High", "adapters", ("adapter-contract",),
      "Resolve explicit model configuration into a versioned family adapter selection.",
      "Known aliases map deterministically.", "Unknown or conflicting configurations fail closed."),
    i("hf-discovery", "Walk Hugging Face modules into canonical components", "v0.1 — Foundation", "Model Introspection", "P0", "Feature", "M", "Medium", "graph", ("component-id", "hf-loader", "family-detection"),
      "Discover modules, parameters and logical heads/channels using the selected family adapter.",
      "Every discovered component has a canonical ID and kind.", "Counts reconcile with model parameters.", "Traversal is deterministic."),
    i("graph-schema", "Define component dependency and coupling graph schema", "v0.1 — Foundation", "Model Introspection", "P0", "Feature", "M", "High", "graph", ("component-id",),
      "Represent nodes and parent, child, consumes, produces, coupled and constrained edges.",
      "Edge semantics and mutation constraints are versioned.", "Graph records serialize without model objects."),
    i("graph-builder", "Build component graph from architecture discovery", "v0.1 — Foundation", "Model Introspection", "P0", "Feature", "L", "High", "graph", ("graph-schema", "hf-discovery"),
      "Construct transformer block, attention Q/K/V/O, MLP gate/up/down, norm and residual relationships.",
      "Coupled closures are complete for supported fixtures.", "Parent/child and dataflow edges are consistent."),
    i("graph-validator", "Validate component graph invariants and mutation closures", "v0.1 — Foundation", "Model Introspection", "P0", "Testing", "M", "High", "graph", ("graph-builder",),
      "Detect dangling IDs, cycles where forbidden, inconsistent reciprocal edges and incomplete coupling closures.",
      "Invalid graphs report exact nodes and violated rules.", "Supported tiny fixtures validate successfully."),
    i("graph-serialization", "Persist and reload versioned component graphs", "v0.1 — Foundation", "Model Introspection", "P1", "Feature", "S", "Low", "graph", ("graph-schema",),
      "Add canonical JSON serialization with schema version and adapter provenance.",
      "Round trips preserve IDs, edges, constraints and ordering.", "Unknown schema versions are rejected."),
    i("gguf-spec-spike", "Map llama.cpp GGUF container and quantization specifications", "v0.1 — Foundation", "Model Introspection", "P0", "Research", "L", "Research", "adapters", ("adapter-contract",),
      "Produce a bounded design mapping container revisions, metadata, tensor alignment and codec sources for native surgery.",
      "Reference exact upstream revisions and test vectors.", "Document F32/F16/BF16, Q8_0, K-quants and IQ families separately.", "Open questions have explicit decisions or follow-up issue keys.",
      tests=("Validate cited fixture metadata with at least two independent GGUF readers.",)),
    i("quant-contract", "Define quantization codec and block-layout abstraction", "v0.1 — Foundation", "Model Introspection", "P0", "Feature", "L", "Research", "adapters", ("gguf-spec-spike",),
      "Define exact block shape, byte layout, alignment, decode, encode, validation and error-estimation interfaces.",
      "Different K-quants cannot be substituted implicitly.", "Codecs report supported axes and shape divisibility constraints."),
    i("gguf-arch-contract", "Define GGUF architecture mapping contract", "v0.1 — Foundation", "Model Introspection", "P0", "Feature", "M", "High", "adapters", ("gguf-spec-spike", "component-id-spec"),
      "Map GGUF metadata and tensor names into canonical components, axis semantics and coupled mutation groups.",
      "Unknown architectures fail closed.", "Contract covers model-specific metadata updates and renaming."),
    i("inspect-cli", "Implement model inspection CLI command", "v0.1 — Foundation", "Foundation", "P1", "Feature", "M", "Low", "cli", ("hf-discovery", "graph-serialization", "logging"),
      "Expose human and JSON inspection for model identity, modules, components and parameter totals.",
      "Output order is stable.", "Errors distinguish dependency, model, revision and adapter failures."),
    i("tiny-fixtures", "Create tiny deterministic model fixtures", "v0.1 — Foundation", "Foundation", "P1", "Testing", "M", "Low", "ci", ("repo-quality",),
      "Provide offline tiny transformer doubles and pinned tiny HF fixture metadata without committing weights.",
      "Unit tests run without network or GPU.", "Fixture generation is deterministic and documented."),
    i("foundation-integration", "Add load discover graph inspect integration test", "v0.1 — Foundation", "Foundation", "P1", "Testing", "M", "Medium", "ci", ("graph-validator", "inspect-cli", "tiny-fixtures"),
      "Exercise a tiny model from loader boundary through discovery, graph validation and CLI JSON.",
      "Test runs on CPU within the CI memory budget.", "Golden component IDs and counts are asserted."),

    # v0.2 — Instrumentation and features
    i("feature-schema", "Define versioned feature record and precision provenance", "v0.2 — Instrumentation", "Feature Extraction", "P0", "Feature", "M", "Medium", "features", ("component-id", "hardware-inventory"),
      "Define scalar/vector features with extractor version, sample context, dtype, quantization and error provenance.",
      "Records distinguish direct quantized, locally dequantized and high-precision sources.", "Schema supports forward-compatible metadata."),
    i("weight-basic", "Extract basic per-tensor weight statistics", "v0.2 — Instrumentation", "Feature Extraction", "P0", "Feature", "M", "Low", "features", ("feature-schema", "hf-discovery"),
      "Extract count, shape, dtype, min, max, mean, variance, standard deviation, L1, L2, Frobenius, max magnitude and sparsity.",
      "Every Linear weight yields conforming records.", "CPU and CUDA tensors are supported and released.",
      tests=("Compare all values with NumPy references including empty/constant edge cases.",)),
    i("weight-distribution", "Extract weight percentiles histograms skewness and kurtosis", "v0.2 — Instrumentation", "Feature Extraction", "P1", "Feature", "M", "Medium", "features", ("weight-basic",),
      "Add configurable percentiles, fixed-schema histograms and stable higher moments.",
      "Bin definitions and percentile interpolation are recorded.", "Constant and low-precision tensors do not produce silent NaNs."),
    i("spectral-exact", "Extract exact singular-value features for bounded matrices", "v0.2 — Instrumentation", "Feature Extraction", "P1", "Feature", "M", "Medium", "features", ("feature-schema",),
      "Compute singular values, decay, spectral norm, effective/stable rank and energy-rank thresholds below configured size limits.",
      "Oversized tensors decline with a reason.", "Numerical tolerances and compute dtype are recorded."),
    i("spectral-approx", "Implement scalable randomized spectral feature extraction", "v0.2 — Instrumentation", "Feature Extraction", "P1", "Performance", "L", "High", "features", ("spectral-exact", "hardware-inventory"),
      "Compute deterministic seeded approximate SVD and low-rank reconstruction errors under memory limits.",
      "Approximation error is measured against exact small cases.", "Peak allocation respects configured workspace bounds."),
    i("calibration-contract", "Define calibration dataset and sample identity contract", "v0.2 — Instrumentation", "Instrumentation", "P0", "Feature", "M", "Medium", "instrumentation", ("config-files",),
      "Represent dataset revision, split, sample IDs, preprocessing, tokenization and deterministic selection.",
      "Same config and seed select the same samples.", "Licensing and trust metadata can be recorded."),
    i("calibration-hf", "Implement Hugging Face text calibration adapter", "v0.2 — Instrumentation", "Instrumentation", "P0", "Feature", "M", "Medium", "instrumentation", ("calibration-contract", "hf-loader"),
      "Stream text samples, tokenize in bounded batches and cache canonical sample manifests.",
      "No full dataset download is required when streaming is supported.", "Revision and tokenizer identity are pinned."),
    i("hook-lifecycle", "Implement exception-safe activation hook lifecycle manager", "v0.2 — Instrumentation", "Instrumentation", "P0", "Feature", "M", "High", "instrumentation", ("component-id", "hf-discovery"),
      "Target canonical components, register hooks in a context manager and remove them after success, exception or interrupt.",
      "Duplicate registration is prevented.", "No hook or captured tensor remains after exit."),
    i("streaming-stats", "Implement mergeable bounded-memory statistics accumulators", "v0.2 — Instrumentation", "Instrumentation", "P0", "Feature", "L", "Medium", "instrumentation", ("feature-schema",),
      "Provide numerically stable count, moments, min/max, RMS, sparsity, percentiles and merge operations.",
      "Chunked and unchunked results agree within tolerance.", "Accumulator memory is independent of token count."),
    i("activation-basic", "Collect per-component activation summary features", "v0.2 — Instrumentation", "Feature Extraction", "P0", "Feature", "M", "Medium", "features", ("hook-lifecycle", "streaming-stats", "calibration-hf"),
      "Collect mean, variance, RMS, zero/activation frequency, max and percentiles over calibration batches.",
      "Token masks are honored.", "Records identify samples and aggregation axes."),
    i("activation-channel", "Collect channel and token-dependent activation features", "v0.2 — Instrumentation", "Feature Extraction", "P1", "Feature", "L", "High", "features", ("activation-basic",),
      "Aggregate per-channel statistics and bounded token-position or token-class summaries.",
      "Output dimension matches graph channel identities.", "Memory is bounded by channels and configured buckets."),
    i("activation-covariance", "Estimate activation covariance in bounded memory", "v0.2 — Instrumentation", "Feature Extraction", "P2", "Feature", "L", "Research", "features", ("activation-channel",),
      "Implement diagonal and sketch-based covariance estimates with explicit rank/budget.",
      "Approximation accuracy and peak memory are reported on small exact cases."),
    i("gradient-collector", "Collect gradients for selected components safely", "v0.2 — Instrumentation", "Instrumentation", "P1", "Feature", "L", "High", "instrumentation", ("hook-lifecycle", "calibration-hf"),
      "Run bounded calibration backward passes, target selected parameters and clear graphs/gradients between batches.",
      "Gradient collection can be disabled.", "Peak GPU retention does not grow across batches."),
    i("gradient-features", "Extract gradient norm weight-gradient and first-order sensitivity", "v0.2 — Instrumentation", "Feature Extraction", "P1", "Feature", "M", "Medium", "features", ("gradient-collector", "feature-schema"),
      "Produce gradient norm, weight×gradient aggregates and first-order removal estimates per component.",
      "Results match analytic tiny-model references.", "Missing gradients are explicit, not zero-filled."),
    i("fisher-spike", "Evaluate practical diagonal Fisher and Hessian approximations", "v0.2 — Instrumentation", "Feature Extraction", "P2", "Research", "L", "Research", "features", ("gradient-features",),
      "Compare at least three sensitivity approximations on two tiny models under fixed time/memory budgets.",
      "Record ranking stability, predictive signal and resource cost.", "Recommend one bounded implementation or document rejection."),
    i("tensor-cosine", "Extract pairwise tensor and output cosine similarities", "v0.2 — Instrumentation", "Feature Extraction", "P1", "Feature", "M", "Medium", "features", ("feature-schema", "streaming-stats"),
      "Compute candidate-restricted cosine similarities without dense all-pairs allocation.",
      "Zero-vector behavior is defined.", "Candidate generation and block size are configurable."),
    i("neuron-correlation", "Extract neuron correlation and duplicate-channel features", "v0.2 — Instrumentation", "Feature Extraction", "P1", "Feature", "L", "High", "features", ("activation-channel", "tensor-cosine"),
      "Rank correlated MLP channels using bounded candidate screening and activation confirmation.",
      "Known duplicate fixtures rank together.", "Runtime and memory scale with configured candidate budget."),
    i("head-similarity-spike", "Evaluate attention-head redundancy metrics", "v0.2 — Instrumentation", "Feature Extraction", "P2", "Research", "L", "Research", "features", ("activation-basic", "tensor-cosine"),
      "Compare cosine, output-correlation and projection/subspace metrics on two small models.",
      "Record runtime, memory and ranking stability.", "Write docs/research/head-similarity.md with a selected metric."),
    i("layer-similarity", "Extract transformer layer similarity features", "v0.2 — Instrumentation", "Feature Extraction", "P2", "Feature", "M", "Medium", "features", ("activation-basic",),
      "Measure residual-stream and output similarity for comparable layers using bounded summaries.",
      "Non-comparable shapes are skipped with provenance.", "Identical-layer fixtures produce maximal similarity."),
    i("topology-features", "Extract component graph topology features", "v0.2 — Instrumentation", "Feature Extraction", "P1", "Feature", "M", "Low", "features", ("graph-builder", "feature-schema"),
      "Emit depth, position, degree, coupling-set size, shape roles and normalized layer index.",
      "Features are deterministic across graph serialization round trips."),
    i("cost-model", "Estimate component parameters FLOPs and activation memory", "v0.2 — Instrumentation", "Feature Extraction", "P0", "Feature", "L", "High", "features", ("graph-builder", "feature-schema"),
      "Estimate parameter count, forward FLOPs and activation bytes for supported components and sequence shapes.",
      "Parameter totals reconcile exactly.", "FLOPs and memory assumptions are emitted alongside values."),
    i("latency-profiler", "Profile component latency with synchronized robust measurements", "v0.2 — Instrumentation", "Feature Extraction", "P1", "Performance", "L", "High", "features", ("hardware-inventory", "hf-discovery"),
      "Measure warmed, synchronized CPU/CUDA latency with medians, dispersion and environment context.",
      "Profiler overhead and sample count are reported.", "CUDA timing is absent rather than fabricated on CPU."),
    i("memory-telemetry", "Collect peak RAM VRAM and allocation telemetry", "v0.2 — Instrumentation", "Instrumentation", "P0", "Performance", "M", "Medium", "instrumentation", ("hardware-inventory",),
      "Measure process RAM, CUDA allocated/reserved peaks and sampled time series around named operations.",
      "CPU-only collection works.", "Sampling can be disabled and does not leak a background thread."),
    i("quant-feature-direct", "Extract safe features directly from quantized GGUF blocks", "v0.2 — Instrumentation", "Feature Extraction", "P1", "Research", "L", "Research", "features", ("feature-schema", "quant-contract", "gguf-spec-spike"),
      "Identify and implement statistics computable without full decode for prioritized codecs, with bounded sampling where exact computation is impossible.",
      "Every value records codec, block coverage and estimated error.", "Unsupported features require local decode rather than silent approximation."),
    i("feature-cache", "Persist and reuse disk-backed feature partitions", "v0.2 — Instrumentation", "Feature Extraction", "P1", "Infrastructure", "M", "Medium", "features", ("feature-schema", "config-files"),
      "Write atomic, partitioned feature records keyed by model revision, component and extractor version.",
      "Partial partitions are not treated as complete.", "Cache invalidates on extractor or input revision change."),
    i("instrumentation-integration", "Add bounded calibrate-and-feature integration test", "v0.2 — Instrumentation", "Instrumentation", "P1", "Testing", "M", "Medium", "ci", ("activation-basic", "weight-basic", "cost-model", "tiny-fixtures"),
      "Calibrate a tiny model and emit static plus activation records under an enforced memory budget.",
      "Golden schema, IDs and feature values are checked.", "All hooks and tensors are released after completion."),
    # v0.3 — Mutation Lab
    i("mutation-contract", "Define transactional mutation interface", "v0.3 — Mutation Lab", "Mutation Engine", "P0", "Feature", "L", "High", "surgery", ("graph-schema", "config-schema"),
      "Define compatibility, affected components, preconditions, apply, rollback, expected deltas and provenance.",
      "Mutation instances are deterministic and serializable.", "Inputs remain immutable unless an explicit safe transaction owns them."),
    i("mutation-planner", "Resolve mutation targets and coupled component closure", "v0.3 — Mutation Lab", "Mutation Engine", "P0", "Feature", "L", "High", "surgery", ("mutation-contract", "graph-validator"),
      "Translate requested IDs into an ordered plan containing all structurally coupled edits and constraints.",
      "Incomplete or ambiguous plans are rejected before model changes.", "Affected IDs and reasons are reported."),
    i("mutation-transaction", "Implement in-memory mutation transaction and rollback", "v0.3 — Mutation Lab", "Mutation Engine", "P0", "Feature", "L", "High", "surgery", ("mutation-planner",),
      "Snapshot only changed state, apply atomically and roll back on failure, interrupt or explicit rejection.",
      "Rollback restores byte-equivalent changed tensors on fixtures.", "Nested or concurrent mutation attempts fail safely."),
    i("component-mask", "Implement generic component output masking", "v0.3 — Mutation Lab", "Mutation Engine", "P0", "Feature", "M", "Medium", "surgery", ("mutation-transaction", "hook-lifecycle"),
      "Mask a graph-addressed component output without physical resizing.",
      "Masking is deterministic and reversible.", "Shape and dtype are unchanged.", "Unsupported output structures fail with context."),
    i("head-mask", "Implement individual attention-head masking", "v0.3 — Mutation Lab", "Mutation Engine", "P0", "Feature", "L", "High", "surgery", ("component-mask", "graph-builder"),
      "Mask one logical attention head at the correct adapter-defined point for supported fixtures.",
      "Only the selected head contribution is zeroed.", "GQA/MQA incompatibilities are reported explicitly."),
    i("mlp-mask", "Implement individual and grouped MLP-channel masking", "v0.3 — Mutation Lab", "Mutation Engine", "P0", "Feature", "M", "Medium", "surgery", ("component-mask", "graph-builder"),
      "Mask adapter-defined MLP intermediate channels and channel groups across the coupled path.",
      "Unselected channels are unchanged.", "Gate/up/down variants are covered by fixtures."),
    i("layer-bypass", "Implement transformer-layer bypass experiment", "v0.3 — Mutation Lab", "Mutation Engine", "P1", "Feature", "M", "High", "surgery", ("mutation-transaction", "graph-builder"),
      "Bypass one transformer block while preserving compatible residual and output structure.",
      "Unsupported residual layouts fail closed.", "Rollback restores original execution."),
    i("expected-deltas", "Estimate mutation parameter FLOP and memory deltas", "v0.3 — Mutation Lab", "Mutation Engine", "P1", "Feature", "M", "Medium", "surgery", ("mutation-planner", "cost-model"),
      "Attach expected physical parameter, FLOP, activation-memory and mask-only deltas to plans.",
      "Mask-only mutations report zero physical parameter reduction.", "Estimates identify assumptions and affected shapes."),
    i("mutation-provenance", "Serialize mutation plans outcomes and identity mappings", "v0.3 — Mutation Lab", "Mutation Engine", "P0", "Feature", "M", "Medium", "surgery", ("mutation-contract", "graph-serialization"),
      "Record input revision, canonical parameters, affected IDs, expected/actual deltas and old-to-new mappings.",
      "Round trips preserve deterministic mutation identity.", "Sensitive local paths can be redacted."),
    i("tier0-load", "Implement Tier 0 load shape and forward validation", "v0.3 — Mutation Lab", "Evaluation", "P0", "Testing", "M", "Medium", "evaluation", ("mutation-transaction", "tiny-fixtures"),
      "Validate model load, canonical graph, tensor shapes and one bounded forward pass.",
      "Failures are classified by stage.", "Validation runs on CPU tiny fixtures."),
    i("tier0-numerics", "Implement Tier 0 NaN Inf and output sanity validation", "v0.3 — Mutation Lab", "Evaluation", "P0", "Testing", "S", "Low", "evaluation", ("tier0-load",),
      "Detect non-finite parameters, activations, logits and loss after mutation.",
      "Reports identify first affected component or output.", "Checks can sample very large tensors deterministically."),
    i("baseline-cache", "Cache immutable baseline logits loss and metrics", "v0.3 — Mutation Lab", "Evaluation", "P0", "Infrastructure", "M", "Medium", "evaluation", ("calibration-contract", "feature-cache"),
      "Cache baseline evaluation artifacts by model, dataset, tokenizer and evaluator versions.",
      "Mutations reuse a matching baseline.", "Mismatched revisions cannot hit the cache."),
    i("perplexity", "Implement token-weighted loss and perplexity evaluator", "v0.3 — Mutation Lab", "Evaluation", "P0", "Feature", "M", "Medium", "evaluation", ("calibration-hf", "tier0-load"),
      "Compute masked token-weighted cross entropy, perplexity and delta from the cached baseline.",
      "Padding and shifted labels are correct.", "Aggregation agrees across batch sizes."),
    i("logit-metrics", "Implement KL divergence and logit similarity evaluator", "v0.3 — Mutation Lab", "Evaluation", "P1", "Feature", "M", "Medium", "evaluation", ("baseline-cache",),
      "Compute teacher-to-candidate KL, cosine similarity and top-k agreement in streaming batches.",
      "Temperature and reduction are recorded.", "Identical logits produce zero KL."),
    i("latency-evaluator", "Implement statistically robust end-to-end latency evaluator", "v0.3 — Mutation Lab", "Evaluation", "P1", "Performance", "M", "High", "evaluation", ("latency-profiler", "tier0-load"),
      "Measure prefill and decode latency with warmup, synchronization and confidence summaries.",
      "Runs record batch, sequence, device and power-relevant context.", "Invalid comparisons are flagged."),
    i("tiered-evaluator", "Orchestrate Tier 0 through Tier 3 evaluation escalation", "v0.3 — Mutation Lab", "Evaluation", "P0", "Feature", "L", "High", "evaluation", ("tier0-numerics", "perplexity", "logit-metrics", "latency-evaluator"),
      "Run configured tiers, stop destructive candidates early and emit explicit escalation decisions.",
      "Tier 0 failure prevents higher tiers.", "Threshold decisions and skipped metrics are recorded."),
    i("experiment-cli", "Implement single-mutation experiment CLI command", "v0.3 — Mutation Lab", "Foundation", "P1", "Feature", "M", "Medium", "cli", ("head-mask", "mlp-mask", "layer-bypass", "tiered-evaluator", "mutation-provenance"),
      "Parse a mutation, execute it transactionally, evaluate and print/save a structured result.",
      "Dry-run displays the resolved plan.", "Ctrl+C invokes rollback and exits nonzero."),
    i("checkpoint-path-safety", "Enforce non-overwriting atomic checkpoint destinations", "v0.3 — Mutation Lab", "Mutation Engine", "P0", "Testing", "M", "High", "surgery", ("config-schema", "mutation-transaction"),
      "Resolve source/destination identities, reject aliases and stage outputs before atomic publication.",
      "Source and destination cannot resolve to the same file or directory by default.", "Interrupted staging never replaces the source."),
    i("masking-golden", "Add golden tests for head channel and layer masking", "v0.3 — Mutation Lab", "Mutation Engine", "P1", "Testing", "M", "Medium", "ci", ("head-mask", "mlp-mask", "layer-bypass", "tier0-numerics"),
      "Pin known tiny models, mutations and expected structural/numeric outcomes.",
      "Golden results include affected IDs and unchanged-neighbor checks.", "Regression changes require explicit fixture-version updates."),

    # v0.4 — Experiment Dataset
    i("experiment-schema", "Define versioned experiment and mutation-example schemas", "v0.4 — Experiment Dataset", "Experiment Dataset", "P0", "Feature", "L", "High", "experiments", ("feature-schema", "mutation-provenance", "tiered-evaluator"),
      "Model targets, components, mutations, baseline/post metrics, deltas, outcomes, hardware, versions, seeds and timings.",
      "Schema distinguishes absent, skipped and failed metrics.", "Quantization control and precision provenance are representable."),
    i("schema-migrations", "Implement ordered experiment schema migrations", "v0.4 — Experiment Dataset", "Experiment Dataset", "P0", "Infrastructure", "M", "High", "experiments", ("experiment-schema",),
      "Create an idempotent migration runner with version table, transactions and backup guidance.",
      "Fresh and upgraded databases reach the same schema.", "Failed migrations roll back."),
    i("sqlite-store", "Implement SQLite experiment metadata store", "v0.4 — Experiment Dataset", "Experiment Dataset", "P0", "Feature", "L", "High", "experiments", ("schema-migrations",),
      "Persist/query runs, inputs, candidates, states, metrics and artifact references with foreign keys.",
      "Concurrent readers and one writer use WAL safely.", "Every record can trace to immutable model and config identity."),
    i("parquet-store", "Implement partitioned Parquet feature and example store", "v0.4 — Experiment Dataset", "Experiment Dataset", "P0", "Feature", "L", "Medium", "dataset", ("experiment-schema",),
      "Write typed feature/example partitions by schema, model and campaign with atomic manifests.",
      "Predicate reads avoid scanning unrelated partitions.", "Partial writes are excluded."),
    i("artifact-store", "Implement content-addressed filesystem artifact store", "v0.4 — Experiment Dataset", "Experiment Dataset", "P0", "Infrastructure", "L", "High", "experiments", ("sqlite-store", "checkpoint-path-safety"),
      "Store immutable artifacts by digest with atomic publication, metadata and reference tracking.",
      "Duplicate content is reused.", "Digest mismatch or incomplete content is rejected."),
    i("experiment-id", "Derive deterministic run experiment and candidate identities", "v0.4 — Experiment Dataset", "Experiment Dataset", "P0", "Feature", "M", "Medium", "experiments", ("experiment-schema", "config-files"),
      "Canonicalize immutable inputs and hash them into stable IDs separate from execution attempts.",
      "Key ordering and local path aliases do not change identity.", "Meaningful config or revision changes do."),
    i("run-state-machine", "Implement atomic resumable experiment state machine", "v0.4 — Experiment Dataset", "Experiment Dataset", "P0", "Feature", "L", "High", "experiments", ("sqlite-store", "experiment-id"),
      "Implement planned, running, evaluating, interrupted, recoverable-OOM, succeeded, rejected and failed transitions.",
      "Invalid transitions are rejected.", "Restart identifies safe next work without duplicating completed stages."),
    i("queue-leases", "Implement resumable work queue leases and heartbeat recovery", "v0.4 — Experiment Dataset", "Experiment Dataset", "P0", "Infrastructure", "L", "High", "experiments", ("run-state-machine",),
      "Claim work with expiring leases, heartbeats and idempotent completion.",
      "Crashed workers release work after timeout.", "Two workers cannot commit the same attempt as current."),
    i("resource-budget", "Implement RAM VRAM disk and runtime budget enforcement", "v0.4 — Experiment Dataset", "Optimization", "P0", "Feature", "L", "High", "experiments", ("hardware-inventory", "memory-telemetry", "run-state-machine"),
      "Preflight and monitor per-stage ceilings with explicit resource-exhausted outcomes.",
      "CPU-only and CUDA budgets are supported.", "Budget violations preserve resumable state."),
    i("gpu-cleanup", "Implement deterministic GPU cleanup between experiments", "v0.4 — Experiment Dataset", "Optimization", "P0", "Performance", "M", "High", "experiments", ("resource-budget",),
      "Release model, hooks, gradients and cache references at worker boundaries and report retained memory.",
      "Repeated tiny experiments have bounded VRAM growth.", "Cleanup works after exceptions."),
    i("oom-recovery", "Recover campaigns from CUDA and host out-of-memory failures", "v0.4 — Experiment Dataset", "Optimization", "P0", "Feature", "L", "High", "experiments", ("gpu-cleanup", "queue-leases"),
      "Classify OOM, reduce batch/chunk size, enable offload where allowed and retry under a bounded policy.",
      "OOM does not terminate unrelated campaign work.", "Retries and adaptations are recorded."),
    i("batch-planner", "Plan calibration batches under measured memory limits", "v0.4 — Experiment Dataset", "Optimization", "P0", "Performance", "M", "High", "experiments", ("resource-budget", "calibration-hf"),
      "Select initial batch size and adapt from telemetry while preserving sample order and metric equivalence.",
      "Batch plans respect maximum tokens and memory.", "Resume continues at an exact sample boundary."),
    i("mixed-precision", "Implement explicit mixed-precision experiment policy", "v0.4 — Experiment Dataset", "Optimization", "P1", "Performance", "M", "Medium", "experiments", ("resource-budget",),
      "Select FP32/FP16/BF16/autocast by device capability and record compute/accumulation dtype.",
      "Unsupported dtype requests fail or use an explicitly logged fallback.", "Metrics do not silently change dtype."),
    i("runtime-telemetry", "Persist stage timing throughput and resource telemetry", "v0.4 — Experiment Dataset", "Experiment Dataset", "P1", "Performance", "M", "Low", "experiments", ("sqlite-store", "memory-telemetry"),
      "Record wall/CPU time, tokens, candidates, peak RAM/VRAM and I/O bytes per stage.",
      "Interrupted stages retain partial telemetry.", "Reports can compare hardware-normalized contexts."),
    i("candidate-enumerator", "Enumerate canonical single-component mutation candidates", "v0.4 — Experiment Dataset", "Experiment Dataset", "P0", "Feature", "M", "Medium", "experiments", ("mutation-planner", "experiment-id"),
      "Generate supported head, channel, component and layer mask candidates from a graph with filters and seed.",
      "Candidates are deterministic and unique.", "Unsupported graph nodes are excluded with counts."),
    i("campaign-runner", "Execute resumable automated mutation campaigns", "v0.4 — Experiment Dataset", "Experiment Dataset", "P0", "Feature", "L", "High", "experiments", ("candidate-enumerator", "queue-leases", "oom-recovery", "tiered-evaluator"),
      "Schedule candidate transactions, reuse baselines, persist outcomes and continue after restart.",
      "Completed candidates are not rerun.", "Failures are isolated and campaign progress is queryable."),
    i("dataset-builder", "Build supervised mutation examples from experiment records", "v0.4 — Experiment Dataset", "Experiment Dataset", "P0", "Feature", "L", "High", "dataset", ("campaign-runner", "parquet-store"),
      "Join pre-mutation features, mutation parameters, contexts and delta targets into versioned examples.",
      "No post-mutation feature leaks into inputs.", "Missingness and failed outcomes follow documented rules."),
    i("dataset-validator", "Validate mutation dataset schema ranges and provenance", "v0.4 — Experiment Dataset", "Experiment Dataset", "P0", "Testing", "M", "Medium", "dataset", ("dataset-builder",),
      "Check types, finite ranges, component references, revisions, target calculations and duplicate IDs.",
      "Validation emits machine-readable errors.", "Corrupt fixtures exercise every rule."),
    i("split-within-model", "Implement component layer and mutation grouped splits", "v0.4 — Experiment Dataset", "Experiment Dataset", "P0", "Feature", "M", "High", "dataset", ("dataset-validator",),
      "Create deterministic grouped train/validation/test splits by component, layer and mutation family.",
      "No configured group crosses partitions.", "Split manifests record seed and group counts."),
    i("split-cross-model", "Implement model and architecture-family held-out splits", "v0.4 — Experiment Dataset", "Generalization", "P0", "Feature", "M", "High", "dataset", ("dataset-validator", "family-detection"),
      "Hold out complete models or architecture families, including train A/B/C test unseen D.",
      "Model revision aliases cannot cross the boundary.", "Insufficient family counts fail with guidance."),
    i("leakage-audit", "Detect dataset leakage across all supported split strategies", "v0.4 — Experiment Dataset", "Experiment Dataset", "P0", "Testing", "L", "High", "dataset", ("split-within-model", "split-cross-model"),
      "Audit exact/near duplicate candidates, shared components, model ancestry and target-derived features.",
      "Injected leakage fixtures are detected.", "A passing audit is required before training."),
    i("repro-capture", "Capture complete experiment reproducibility manifest", "v0.4 — Experiment Dataset", "Experiment Dataset", "P0", "Feature", "M", "Medium", "experiments", ("hardware-inventory", "experiment-id", "artifact-store"),
      "Capture git/config/model/dataset/tokenizer revisions, seed, Python/PyTorch/CUDA, hardware and lock digest.",
      "Manifest is immutable and linked to every run.", "Missing non-optional revision fields block reproducible status."),
    i("dataset-integration", "Add interrupt-resume campaign-to-dataset integration test", "v0.4 — Experiment Dataset", "Experiment Dataset", "P1", "Testing", "L", "High", "ci", ("campaign-runner", "dataset-builder", "leakage-audit", "tiny-fixtures"),
      "Interrupt a tiny campaign, resume it and build validated split datasets.",
      "No completed candidate duplicates.", "Resumed output is equivalent to uninterrupted output."),

    # v0.5 — First Surgeon
    i("target-builder", "Derive supervised targets and safe-mutation labels", "v0.5 — First Surgeon", "Baseline Surgeon", "P0", "Feature", "M", "High", "surgeon", ("dataset-builder",),
      "Calculate delta loss/perplexity/behavior/latency/parameters and threshold-safe labels from baselines.",
      "Direction and units are schema-defined.", "Missing metrics produce explicit target masks."),
    i("random-baseline", "Implement seeded random candidate ranking baseline", "v0.5 — First Surgeon", "Baseline Surgeon", "P0", "Research", "S", "Low", "surgeon", ("candidate-enumerator",),
      "Rank candidates reproducibly and emit selection propensities.",
      "Same seed and pool produce identical order.", "Tie and subset behavior is defined."),
    i("magnitude-baseline", "Implement magnitude pruning ranking baseline", "v0.5 — First Surgeon", "Baseline Surgeon", "P0", "Research", "M", "Medium", "surgeon", ("weight-basic", "candidate-enumerator"),
      "Rank compatible candidates using normalized magnitude aggregates with declared grouping.",
      "Scores match reference calculations.", "Cross-shape normalization is configurable and recorded."),
    i("heuristic-baseline", "Implement composable hand-crafted surgeon baseline", "v0.5 — First Surgeon", "Baseline Surgeon", "P0", "Feature", "M", "Medium", "surgeon", ("target-builder", "magnitude-baseline", "activation-basic"),
      "Combine magnitude, activation, sensitivity and redundancy signals through versioned weights and rules.",
      "Missing features follow explicit policy.", "Decision traces identify contributing rules."),
    i("training-matrix", "Build typed surgeon training matrices and preprocessing", "v0.5 — First Surgeon", "Baseline Surgeon", "P0", "Feature", "L", "High", "surgeon", ("target-builder", "leakage-audit"),
      "Materialize numeric/categorical features, missingness, sample weights and split manifests without fitting on validation/test.",
      "Preprocessing is fitted on train only.", "Feature names and schema versions remain traceable."),
    i("linear-regressor", "Train regularized linear delta-metric baselines", "v0.5 — First Surgeon", "Baseline Surgeon", "P0", "Feature", "M", "Medium", "surgeon", ("training-matrix",),
      "Train ridge/elastic-net models for delta perplexity and other available continuous targets.",
      "Hyperparameters and coefficients are persisted.", "Validation selection never reads test labels."),
    i("logistic-classifier", "Train logistic safe-mutation classifier baseline", "v0.5 — First Surgeon", "Baseline Surgeon", "P0", "Feature", "M", "Medium", "surgeon", ("training-matrix",),
      "Train class-weighted regularized classification with probability output.",
      "Class threshold and imbalance handling are recorded.", "Single-class splits fail with guidance."),
    i("tree-regressor", "Train LightGBM delta-perplexity regressor", "v0.5 — First Surgeon", "Baseline Surgeon", "P0", "Feature", "L", "Medium", "surgeon", ("training-matrix",),
      "Train CPU-friendly LightGBM regression with bounded threads, early stopping and persisted feature metadata.",
      "Model reload reproduces predictions.", "Training fits reference 64 GB RAM limits."),
    i("tree-classifier", "Train LightGBM safe-mutation classifier", "v0.5 — First Surgeon", "Baseline Surgeon", "P0", "Feature", "L", "Medium", "surgeon", ("training-matrix",),
      "Train probability classifier with imbalance handling, early stopping and deterministic seeds.",
      "Model reload reproduces probabilities.", "Metrics include AUC and precision at top N."),
    i("small-mlp", "Train small MLP surgeon baseline", "v0.5 — First Surgeon", "Baseline Surgeon", "P1", "Feature", "L", "High", "surgeon", ("training-matrix",),
      "Train a bounded tabular MLP with early stopping, normalization and CPU/CUDA support.",
      "Parameter count and peak VRAM are reported.", "Seeds control initialization and data order."),
    i("surgeon-metrics", "Implement surgeon regression ranking and classification metrics", "v0.5 — First Surgeon", "Baseline Surgeon", "P0", "Feature", "M", "Medium", "surgeon", ("target-builder",),
      "Calculate MAE, RMSE, R², AUC, PR-AUC, calibration error, precision/recall at N and constraint violations.",
      "Metrics handle grouped bootstrap confidence intervals.", "Undefined cases are explicit."),
    i("model-registry", "Persist surgeon models schemas and evaluation cards", "v0.5 — First Surgeon", "Baseline Surgeon", "P1", "Infrastructure", "M", "Medium", "surgeon", ("artifact-store", "surgeon-metrics"),
      "Store trained artifact, preprocessing, feature/target schemas, split, metrics and provenance as one immutable version.",
      "Incompatible feature schemas reject inference.", "Cards identify training models and quantizations."),
    i("train-cli", "Implement train-surgeon and predict CLI commands", "v0.5 — First Surgeon", "Foundation", "P1", "Feature", "M", "Medium", "cli", ("heuristic-baseline", "linear-regressor", "logistic-classifier", "tree-regressor", "tree-classifier", "model-registry"),
      "Train a selected baseline from a dataset and score compatible candidates from a model.",
      "Commands emit resolved versions and split metrics.", "Inference refuses missing required features."),
    i("first-loop", "Run first static-plus-activation LightGBM proof", "v0.5 — First Surgeon", "Baseline Surgeon", "P0", "Research", "L", "Research", "surgeon", ("train-cli", "dataset-integration", "surgeon-metrics", "random-baseline"),
      "Generate thousands of mask examples on a small model and compare LightGBM with magnitude and random rankings.",
      "Report AUC, delta-PPL MAE/RMSE and precision at top N.", "Use held-out components and publish config, revisions, seeds and resource use."),

    # v0.6 — Active Surgeon
    i("prediction-calibration", "Calibrate safe-mutation probabilities", "v0.6 — Active Surgeon", "Active Learning", "P0", "Feature", "M", "Medium", "surgeon", ("tree-classifier", "surgeon-metrics"),
      "Fit Platt and isotonic calibrators using validation data only and select by documented metric.",
      "Reliability curves and ECE/Brier scores are stored.", "Calibration never uses test labels."),
    i("tree-uncertainty", "Estimate tree surgeon epistemic uncertainty", "v0.6 — Active Surgeon", "Active Learning", "P0", "Research", "L", "Research", "active-learning", ("tree-regressor", "tree-classifier"),
      "Compare ensembles, bootstrap and quantile methods under a fixed CPU budget.",
      "Coverage, ranking utility and cost are reported.", "Selected method exposes versioned uncertainty values."),
    i("mlp-uncertainty", "Estimate MLP surgeon uncertainty", "v0.6 — Active Surgeon", "Active Learning", "P2", "Research", "L", "Research", "active-learning", ("small-mlp",),
      "Compare deep ensembles and Monte Carlo dropout under a fixed compute budget.",
      "Calibration and active-selection value are reported.", "Implementation can be disabled without affecting tree workflows."),
    i("candidate-pool", "Generate large cheap active-learning candidate pools", "v0.6 — Active Surgeon", "Active Learning", "P0", "Feature", "L", "High", "active-learning", ("candidate-enumerator", "model-registry"),
      "Generate up to 100,000 canonical graph-valid candidate descriptions without model mutation.",
      "Pool generation is bounded and resumable.", "Each candidate has cheap features and provenance."),
    i("candidate-scoring", "Batch surgeon scoring for candidate pools", "v0.6 — Active Surgeon", "Active Learning", "P0", "Performance", "M", "Medium", "active-learning", ("candidate-pool", "prediction-calibration"),
      "Score utility, outcomes, safe probability and uncertainty in bounded batches.",
      "Results are stable across batch sizes.", "Schema-incompatible candidates are quarantined."),
    i("candidate-dedup", "Deduplicate candidates and evaluated mutation equivalence classes", "v0.6 — Active Surgeon", "Active Learning", "P0", "Feature", "M", "High", "active-learning", ("candidate-pool", "experiment-id"),
      "Canonicalize order-insensitive component sets and adapter-declared equivalent mutations.",
      "Already completed/in-flight candidates are excluded.", "False equivalence fixtures remain distinct."),
    i("diversity-sampling", "Select diverse candidates in feature and topology space", "v0.6 — Active Surgeon", "Active Learning", "P1", "Feature", "L", "High", "active-learning", ("candidate-scoring",),
      "Implement scalable clustering or farthest-first selection with categorical/topology handling.",
      "Selection is deterministic under a seed.", "Peak memory is bounded for 100,000 candidates."),
    i("explore-exploit", "Combine uncertainty utility and diversity selection policies", "v0.6 — Active Surgeon", "Active Learning", "P0", "Feature", "L", "Research", "active-learning", ("tree-uncertainty", "diversity-sampling"),
      "Allocate explicit fractions to high-value, uncertain and diverse candidates with configurable policy.",
      "Every selection records reason and propensity.", "Zero/oversubscribed budgets behave deterministically."),
    i("experiment-budget", "Enforce active-learning experiment budgets", "v0.6 — Active Surgeon", "Active Learning", "P0", "Feature", "M", "Medium", "active-learning", ("resource-budget", "explore-exploit"),
      "Limit experiments by count, wall time, tier cost, GPU time and disk use.",
      "Scheduler stops cleanly at boundaries.", "Unused failed-attempt budget policy is explicit."),
    i("active-scheduler", "Schedule selected active-learning evaluations", "v0.6 — Active Surgeon", "Active Learning", "P0", "Feature", "L", "High", "active-learning", ("candidate-dedup", "experiment-budget", "campaign-runner"),
      "Submit selected candidates to the resumable campaign queue and feed completed examples back into datasets.",
      "Partial batches resume without reselection.", "Selection metadata links to resulting experiments."),
    i("retraining-triggers", "Trigger versioned surgeon retraining from new evidence", "v0.6 — Active Surgeon", "Active Learning", "P1", "Feature", "M", "Medium", "active-learning", ("active-scheduler", "model-registry"),
      "Retrain by example count, elapsed budget or drift signals and compare challenger with incumbent.",
      "Promotion criteria are explicit.", "Failed challengers do not replace incumbents."),
    i("active-learning-study", "Measure active-learning sample efficiency", "v0.6 — Active Surgeon", "Active Learning", "P0", "Research", "L", "Research", "active-learning", ("retraining-triggers", "random-baseline"),
      "Compare active, random and utility-only selection across equal evaluation budgets.",
      "Plot predictive performance versus experiments and compute area under learning curve.", "Publish seeds, confidence intervals and negative results."),

    # v0.7 — Structural and Native GGUF Surgery
    i("identity-remap", "Implement post-surgery component identity remapping", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P0", "Feature", "L", "High", "graph", ("mutation-provenance", "graph-validator"),
      "Represent retained, removed, renumbered, split and merged component mappings after physical edits.",
      "Mappings compose across sequential surgeries.", "Removed IDs cannot resolve silently to a different component."),
    i("physical-plan", "Compile mutation plans into physical tensor edits", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P0", "Feature", "L", "High", "surgery", ("mutation-planner", "identity-remap"),
      "Resolve tensor axes, index transforms, coupled edits, new shapes, metadata updates and expected storage deltas.",
      "Plan validation occurs before allocating changed tensors.", "Plans are format-neutral and serializable."),
    i("hf-mlp-remove", "Physically remove structured MLP channels in HF models", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P0", "Feature", "L", "High", "surgery", ("physical-plan", "mlp-mask"),
      "Resize adapter-defined gate/up/down tensors and configuration for selected channel groups.",
      "New shapes and parameter counts match plan.", "Forward pass and save/reload succeed.", "Mask and physical outputs agree before repair within tolerance."),
    i("hf-head-remove", "Physically remove attention heads in HF models", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P0", "Feature", "L", "High", "surgery", ("physical-plan", "head-mask"),
      "Resize coupled Q/K/V/O projections and update head metadata for supported MHA/GQA layouts.",
      "Invalid KV divisibility is rejected.", "Save/reload and forward validation pass."),
    i("hf-layer-remove", "Physically remove transformer layers in HF models", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P1", "Feature", "L", "High", "surgery", ("physical-plan", "layer-bypass"),
      "Remove full block modules, renumber canonical mappings and update layer-count configuration.",
      "Remaining weights are unchanged.", "Save/reload and forward validation pass."),
    i("hf-low-rank", "Replace selected Linear weights with low-rank approximations", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P1", "Feature", "L", "High", "surgery", ("physical-plan", "spectral-approx"),
      "Compute bounded SVD approximation and install adapter-supported factorized or reconstructed representation.",
      "Requested rank and reconstruction error are recorded.", "Parameter/FLOP deltas match actual modules."),
    i("safetensors-save", "Write physically modified safetensors checkpoints atomically", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P0", "Feature", "L", "High", "adapters", ("safetensors-index", "checkpoint-path-safety", "identity-remap"),
      "Write new single/sharded checkpoints, index and configuration to a staging destination then publish.",
      "Original shards remain unchanged.", "Reloaded tensor names, shapes and checksums match the plan."),
    i("gguf-mmap", "Implement read-only memory-mapped GGUF container parser", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P0", "Feature", "L", "High", "adapters", ("gguf-spec-spike",),
      "Parse supported GGUF headers, typed metadata, tensor descriptors, alignment and byte ranges without loading payloads.",
      "A 40 GB sparse fixture has bounded resident memory.", "Malformed lengths, overlaps and offsets fail safely."),
    i("gguf-tensor-index", "Build lazy GGUF tensor index and chunk reader", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P0", "Feature", "M", "High", "adapters", ("gguf-mmap", "quant-contract"),
      "Expose validated tensor metadata and bounded byte/block range reads through stable handles.",
      "Reads cannot escape a tensor or file range.", "Tensor payloads are not materialized until requested."),
    i("gguf-graph", "Discover GGUF components and coupling graph", "v0.7 — Structural and Native GGUF Surgery", "Model Introspection", "P0", "Feature", "L", "High", "graph", ("gguf-tensor-index", "gguf-arch-contract", "graph-schema"),
      "Map supported GGUF metadata/tensors into canonical component nodes, axes and coupling edges.",
      "Parameter totals and tensor shapes reconcile.", "Unknown family or missing required tensor fails closed."),
    i("memory-modes", "Implement full tensor and streaming memory-mode planner", "v0.7 — Structural and Native GGUF Surgery", "Optimization", "P0", "Feature", "L", "High", "experiments", ("resource-budget", "gguf-tensor-index"),
      "Choose or honor full/tensor/streaming modes from RAM, VRAM, scratch disk and operation estimates.",
      "Each plan exposes peak resource estimates.", "Automatic fallback never exceeds a hard user ceiling."),
    i("disk-backed-tensor", "Implement bounded disk-backed tensor intermediates", "v0.7 — Structural and Native GGUF Surgery", "Optimization", "P0", "Infrastructure", "L", "High", "adapters", ("memory-modes", "artifact-store"),
      "Provide chunked temporary arrays with checksums, lifecycle cleanup and resumable manifests.",
      "Resident memory remains bounded by chunk size.", "Stale scratch artifacts are detected and recoverable."),
    i("disk-preflight", "Preflight GGUF output and scratch disk requirements", "v0.7 — Structural and Native GGUF Surgery", "Optimization", "P0", "Feature", "M", "High", "adapters", ("memory-modes", "checkpoint-path-safety"),
      "Estimate output, scratch, alignment and safety margin before writes and monitor remaining space.",
      "Insufficient space fails before source changes.", "Sparse/copy optimizations are estimates, not assumed guarantees."),
    i("gguf-writer", "Implement transactional streaming GGUF output writer", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P0", "Feature", "L", "High", "adapters", ("gguf-mmap", "disk-preflight", "checkpoint-path-safety"),
      "Write metadata, descriptors, aligned tensor streams and final integrity metadata to a staging file.",
      "Output offsets and alignment validate.", "Destination appears atomically only after successful finalize."),
    i("gguf-direct-copy", "Copy unchanged GGUF tensors byte-for-byte", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P0", "Performance", "M", "High", "adapters", ("gguf-tensor-index", "gguf-writer"),
      "Stream unchanged tensor byte ranges directly from source into the output at new aligned offsets.",
      "Payload checksums are identical.", "Peak buffer use respects streaming configuration."),
    i("gguf-write-resume", "Resume interrupted GGUF output construction", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P0", "Feature", "L", "High", "adapters", ("gguf-writer", "gguf-direct-copy", "run-state-machine"),
      "Checkpoint completed metadata/tensor ranges and verify them before resuming from a staging output.",
      "Power-loss simulation never publishes an incomplete model.", "Changed input/plan invalidates resume safely."),
    i("codec-vectors", "Build quantization codec conformance vector suite", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P0", "Testing", "L", "High", "adapters", ("quant-contract",),
      "Generate/import license-compatible upstream vectors for every supported type and edge block.",
      "Vectors include encoded bytes, decoded values, shapes and upstream revision.", "Tests detect byte-order and packing errors."),
    i("codec-float", "Implement F32 F16 and BF16 GGUF codecs", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P0", "Feature", "M", "Medium", "adapters", ("codec-vectors",),
      "Decode, encode, stream and validate unquantized GGUF tensor types.",
      "Round-trip bytes or values meet type-appropriate guarantees.", "Odd supported shapes and endian behavior are covered."),
    i("codec-q8", "Implement Q8_0 GGUF codec", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P0", "Feature", "L", "High", "adapters", ("codec-vectors",),
      "Implement exact block-aware Q8_0 decode, encode, range access and validation from the upstream specification.",
      "Conformance vectors pass.", "Quantization error and block alignment are reported."),
    i("codec-q6k", "Implement Q6_K GGUF codec", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P0", "Feature", "L", "High", "adapters", ("codec-vectors",),
      "Implement exact super-block Q6_K decode, encode, range access and validation.",
      "Conformance vectors pass.", "Q6_K layout is not shared implicitly with another K-quant."),
    i("codec-q5k", "Implement Q5_K variants GGUF codec", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P0", "Feature", "L", "High", "adapters", ("codec-vectors",),
      "Implement and distinguish applicable Q5_K variants including practical Q5_K_M metadata behavior.",
      "Conformance vectors pass per actual tensor type.", "Variant-specific scales and block rules are validated."),
    i("codec-q4k", "Implement Q4_K variants GGUF codec", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P0", "Feature", "L", "High", "adapters", ("codec-vectors",),
      "Implement and distinguish applicable Q4_K variants including practical Q4_K_M metadata behavior.",
      "Conformance vectors pass per actual tensor type.", "Variant-specific scales and block rules are validated."),
    i("codec-q3q2", "Implement Q3_K and Q2_K GGUF codecs", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P1", "Feature", "L", "High", "adapters", ("codec-vectors",),
      "Implement exact separate Q3_K and Q2_K block codecs and validators.",
      "Conformance vectors pass for both.", "APIs cannot treat their blocks as interchangeable."),
    i("iq-spike", "Bound native IQ-family surgery support", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P1", "Research", "L", "Research", "adapters", ("codec-vectors",),
      "Inventory current IQ tensor types, codebook dependencies, encoding availability and practical priorities.",
      "Test at least IQ2 and IQ4 family samples.", "Produce an implementation matrix with explicit supported/read-only/deferred decisions."),
    i("codec-iq-priority", "Implement prioritized IQ-family GGUF codecs", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P1", "Feature", "L", "High", "adapters", ("iq-spike",),
      "Implement decode/encode/validation for the IQ types selected by the bounded spike.",
      "Every claimed type passes upstream conformance vectors.", "Unimplemented IQ types fail as unsupported before mutation."),
    i("quant-alignment", "Validate quantization block and axis alignment for mutations", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P0", "Feature", "L", "High", "surgery", ("physical-plan", "codec-q8", "codec-q6k", "codec-q5k", "codec-q4k"),
      "Map changed axes to codec block layout, verify representable new shapes and propose explicit aligned remaps where allowed.",
      "Naive packed-byte deletion is impossible through the API.", "Unrepresentable requests fail before decode or output."),
    i("selective-dequant", "Dequantize only affected GGUF tensor blocks", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P0", "Feature", "L", "High", "surgery", ("gguf-tensor-index", "quant-alignment", "memory-modes", "disk-backed-tensor"),
      "Read and decode the minimum codec-aligned regions required by a physical plan into configured float precision.",
      "Touched byte/block ranges are recorded.", "Peak RAM remains within the plan for large sparse fixtures."),
    i("selective-requant", "Requantize and validate changed GGUF tensor blocks", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P0", "Feature", "L", "High", "surgery", ("selective-dequant", "gguf-writer"),
      "Encode changed tensors/chunks with the original or explicitly selected codec and stream them to output.",
      "Encoded shape, block count and payload size validate.", "Quantization error summaries are emitted."),
    i("gguf-llama-adapter", "Implement Llama GGUF architecture surgery adapter", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P0", "Feature", "L", "High", "adapters", ("gguf-graph", "family-detection"),
      "Map Llama tensor names, axes, MHA/GQA metadata, MLP coupling and layer naming for physical edits.",
      "Supported versions pass real metadata fixtures.", "Unexpected required tensors fail closed."),
    i("gguf-qwen-adapter", "Implement Qwen GGUF architecture surgery adapter", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P0", "Feature", "L", "High", "adapters", ("gguf-graph", "family-detection"),
      "Map Qwen tensor names, axes, attention/MLP metadata and family-specific constraints.",
      "Supported Qwen fixtures build valid graphs.", "Architecture-version differences are explicit."),
    i("gguf-mistral-adapter", "Implement Mistral GGUF architecture surgery adapter", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P1", "Feature", "L", "High", "adapters", ("gguf-graph", "family-detection"),
      "Map Mistral tensor names, sliding-window metadata, GQA and MLP constraints.",
      "Supported fixtures build valid graphs.", "Unknown variants fail closed."),
    i("gguf-gemma-adapter", "Implement Gemma GGUF architecture surgery adapter", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P1", "Feature", "L", "High", "adapters", ("gguf-graph", "family-detection"),
      "Map Gemma tensor names, attention/MLP dimensions, normalization and family constraints.",
      "Supported fixtures build valid graphs.", "Unknown variants fail closed."),
    i("gguf-mlp-plan", "Plan coupled native GGUF MLP channel removal", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P0", "Feature", "L", "High", "surgery", ("quant-alignment", "gguf-llama-adapter", "gguf-qwen-adapter"),
      "Resolve channel groups across gate/up/down axes, new shapes and required metadata for selected families.",
      "Plan loads only coupled tensors.", "Expected parameter/file-size changes reconcile with new descriptors."),
    i("gguf-mlp-remove", "Execute native quantized GGUF MLP channel removal", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P0", "Feature", "L", "High", "surgery", ("gguf-mlp-plan", "selective-requant", "gguf-direct-copy", "gguf-write-resume"),
      "Decode affected blocks, remove aligned channels, requantize changed tensors and stream a new GGUF.",
      "Untouched tensor payloads are byte-identical.", "No full floating-point model copy is created.", "Output graph matches the plan."),
    i("gguf-head-spike", "Resolve native GGUF attention-head removal rules", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P0", "Research", "L", "Research", "surgery", ("quant-alignment", "gguf-llama-adapter", "gguf-qwen-adapter"),
      "Specify Q/K/V/O edits for MHA, GQA and MQA, including KV counts, head dimensions and codec alignment.",
      "Test plans on Llama and Qwen fixtures.", "Document representable removals and safe rejection rules."),
    i("gguf-head-remove", "Execute native quantized GGUF attention-head removal", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P1", "Feature", "L", "High", "surgery", ("gguf-head-spike", "selective-requant", "gguf-direct-copy", "gguf-write-resume"),
      "Physically edit all coupled attention tensors and metadata for supported head-removal plans.",
      "MHA/GQA outputs load and forward-validate.", "Invalid KV relationships are rejected before writing."),
    i("gguf-layer-remove", "Execute native quantized GGUF transformer-layer removal", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P1", "Feature", "L", "High", "surgery", ("gguf-llama-adapter", "gguf-qwen-adapter", "gguf-writer", "gguf-direct-copy", "identity-remap"),
      "Omit selected complete block tensors, rename following tensors where required and update layer metadata.",
      "Remaining tensor payloads are byte-identical.", "Output metadata and canonical mappings are consistent."),
    i("gguf-low-rank", "Replace selected quantized GGUF tensors with low-rank approximations", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P1", "Feature", "L", "High", "surgery", ("selective-dequant", "selective-requant", "spectral-approx"),
      "Decode one selected tensor, compute bounded low-rank reconstruction, requantize and replace it without full-model decode.",
      "Rank, reconstruction and requantization errors are recorded.", "Unchanged tensors remain byte-identical."),
    i("hidden-dim-spike", "Evaluate coordinated embedding and hidden-dimension surgery", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P2", "Research", "L", "Research", "surgery", ("physical-plan", "gguf-graph"),
      "Map global coupling, rotary/norm constraints and quantization alignment for two families under a bounded study.",
      "Produce feasible operation classes or a documented rejection.", "No physical mutation is implemented without complete coupling proof."),
    i("requant-control", "Implement matched requantization-only control mutations", "v0.7 — Structural and Native GGUF Surgery", "Evaluation", "P0", "Research", "M", "High", "evaluation", ("selective-dequant", "selective-requant"),
      "Decode and re-encode affected regions without structural change using the identical code path and seed.",
      "Reports separate requantization delta, surgery delta and combined delta.", "Control touches the same codec-aligned ranges."),
    i("llamacpp-load", "Validate generated GGUF load and forward pass with llama.cpp", "v0.7 — Structural and Native GGUF Surgery", "Evaluation", "P0", "Testing", "L", "High", "evaluation", ("gguf-writer",),
      "Integrate pinned llama.cpp tooling to inspect, load and run a bounded forward/generation sanity check.",
      "Tool version and command are captured.", "A generated GGUF is unsuccessful until this validation passes."),
    i("llamacpp-ppl", "Benchmark GGUF perplexity with llama.cpp", "v0.7 — Structural and Native GGUF Surgery", "Evaluation", "P0", "Feature", "M", "Medium", "evaluation", ("llamacpp-load", "calibration-contract"),
      "Run pinned perplexity tooling on canonical sample manifests and parse structured results.",
      "Baseline and candidate use identical tokenizer/context settings.", "Failures preserve raw logs."),
    i("llamacpp-throughput", "Benchmark GGUF prompt and generation throughput", "v0.7 — Structural and Native GGUF Surgery", "Evaluation", "P1", "Performance", "M", "High", "evaluation", ("llamacpp-load", "memory-telemetry"),
      "Measure prompt-processing and generation tokens/s, latency, peak RAM/VRAM and context-size behavior.",
      "Warmup, threads, offload layers and context are recorded.", "Comparisons flag configuration drift."),
    i("llamacpp-quant-tools", "Integrate pinned llama.cpp quantization tooling", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P1", "Infrastructure", "M", "Medium", "adapters", ("gguf-spec-spike", "repro-capture"),
      "Discover/configure supported quantization binaries, validate versions and capture invocations without bundling binaries.",
      "Missing tools produce actionable errors.", "Compatibility checks reject unsupported revisions."),
    i("gguf-compat-suite", "Build native GGUF codec and architecture compatibility suite", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P0", "Testing", "L", "High", "ci", ("gguf-mistral-adapter", "gguf-gemma-adapter", "codec-q3q2", "codec-iq-priority", "llamacpp-load"),
      "Exercise supported family×codec×operation cells with small fixtures and track explicit unsupported cells.",
      "No claimed support lacks a load/forward test.", "Upstream format changes are detected by scheduled tests."),
    i("native-gguf-proof", "Demonstrate low-memory Q4_K_M native MLP surgery", "v0.7 — Structural and Native GGUF Surgery", "Structural Surgery", "P0", "Research", "L", "Research", "surgery", ("gguf-mlp-remove", "requant-control", "llamacpp-ppl", "llamacpp-throughput"),
      "Mmap a small Q4_K_M GGUF, remove one aligned MLP channel group, write and validate a new GGUF without a full FP16/BF16 copy.",
      "Report file/parameter, perplexity, generation, throughput and peak RAM changes.", "Peak memory demonstrates bounded tensor/streaming operation.", "Untouched tensor checksums are preserved."),

    # v0.8 — Cross-Model Generalization
    i("model-ladder", "Define permissive multi-family model evaluation ladder", "v0.8 — Cross-Model Generalization", "Generalization", "P0", "Research", "M", "Research", "evaluation", ("family-detection", "repro-capture"),
      "Select maintained models near 100M, 300M, 500M, 1B, 1.5B, 3B and 7B across families with licenses and revisions.",
      "Each target has purpose, hardware mode and dataset compatibility.", "Weights are never committed to Git."),
    i("architecture-matrix", "Publish HF and GGUF architecture compatibility matrix", "v0.8 — Cross-Model Generalization", "Generalization", "P1", "Documentation", "M", "Medium", "adapters", ("model-ladder", "gguf-compat-suite", "safetensors-save"),
      "Document analysis, masking and physical operation support per family, format and codec.",
      "Matrix is generated from adapter capability tests where practical.", "Unknown cells are not labeled supported."),
    i("q1-static", "Q1 measure static-feature prediction of safe pruning", "v0.8 — Cross-Model Generalization", "Generalization", "P0", "Research", "L", "Research", "surgeon", ("first-loop", "model-ladder"),
      "Train/evaluate surgeon models using static features only across at least three target models.",
      "Report held-out AUC, MAE/RMSE and top-N precision with confidence intervals."),
    i("q2-activation", "Q2 measure incremental value of activation features", "v0.8 — Cross-Model Generalization", "Generalization", "P0", "Research", "L", "Research", "surgeon", ("q1-static", "activation-channel"),
      "Run paired static versus static-plus-activation ablations on identical splits and budgets.",
      "Report predictive gain, collection time and memory cost."),
    i("q3-gradient", "Q3 measure incremental value of gradient features", "v0.8 — Cross-Model Generalization", "Generalization", "P1", "Research", "L", "Research", "surgeon", ("q2-activation", "gradient-features"),
      "Run paired ablations adding gradient/sensitivity features under identical splits.",
      "Report predictive gain and additional compute/memory cost."),
    i("q4-baselines", "Q4 compare learned surgeon with magnitude and random pruning", "v0.8 — Cross-Model Generalization", "Generalization", "P0", "Research", "L", "Research", "surgeon", ("q1-static", "random-baseline", "magnitude-baseline"),
      "Compare equal-budget candidate rankings and achieved quality/cost tradeoffs.",
      "Use paired seeds, confidence intervals and constraint-violation rates."),
    i("q5-cross-model", "Q5 evaluate surgeon transfer to unseen models", "v0.8 — Cross-Model Generalization", "Generalization", "P0", "Research", "L", "Research", "surgeon", ("q2-activation", "split-cross-model", "model-ladder"),
      "Train on selected models and test on a completely unseen model of a represented family.",
      "No target-model examples or fitted preprocessing enter training.", "Report within- versus cross-model degradation."),
    i("q6-cross-family", "Q6 evaluate training across architectures and unseen-family transfer", "v0.8 — Cross-Model Generalization", "Generalization", "P1", "Research", "L", "Research", "surgeon", ("q5-cross-model", "architecture-matrix"),
      "Compare single-family, multi-family and held-out-family training protocols.",
      "Report whether multi-family training improves transfer and where schemas fail."),
    i("q7-active", "Q7 validate active-learning experiment reduction across models", "v0.8 — Cross-Model Generalization", "Generalization", "P0", "Research", "L", "Research", "active-learning", ("active-learning-study", "model-ladder"),
      "Repeat equal-performance/equal-budget active versus random acquisition on multiple models.",
      "Report experiments and GPU-hours required to reach target performance."),
    i("q8-iterative", "Q8 compare iterative with one-shot pruning", "v0.8 — Cross-Model Generalization", "Generalization", "P1", "Research", "L", "Research", "search", ("q4-baselines", "hf-mlp-remove", "native-gguf-proof"),
      "Compare matched total compression using sequential evaluate/retrain versus one-shot ranking.",
      "Report quality, latency, accumulated quantization error and experiment cost."),
    i("quant-feature-study", "Measure quantized feature reliability across precisions", "v0.8 — Cross-Model Generalization", "Generalization", "P0", "Research", "L", "Research", "features", ("quant-feature-direct", "codec-q4k", "codec-q8", "model-ladder"),
      "Compare direct/dequantized Q4/Q5/Q6/Q8 features with high-precision references across models.",
      "Estimate per-feature bias, variance, ranking stability and resource cost.", "Update feature provenance error models."),
    i("quant-aware-surgeon", "Add quantization and hardware context to surgeon inputs", "v0.8 — Cross-Model Generalization", "Generalization", "P0", "Feature", "L", "High", "surgeon", ("quant-feature-study", "training-matrix", "requant-control"),
      "Encode codec, bits/weight, estimated error, source precision and hardware context without target leakage.",
      "Predictions can differ for BF16 and Q4 sources.", "Ablations quantify context value."),
    i("quant-loss-study", "Separate surgery and requantization quality effects", "v0.8 — Cross-Model Generalization", "Generalization", "P0", "Research", "L", "Research", "evaluation", ("requant-control", "quant-aware-surgeon", "llamacpp-ppl"),
      "Run matched no-op requantization and surgery-plus-requantization experiments across prioritized codecs.",
      "Report main effects, interaction and uncertainty.", "Control and treatment touch identical aligned regions."),
    i("scale-study", "Measure consumer-hardware scaling from 100M to 7B", "v0.8 — Cross-Model Generalization", "Generalization", "P1", "Performance", "L", "Research", "experiments", ("model-ladder", "memory-modes", "runtime-telemetry"),
      "Benchmark analysis, feature, mutation and evaluation stages across the model ladder on reference-class hardware.",
      "Report time, peak RAM/VRAM/disk and failures.", "Document practical defaults for each scale."),

    # v0.9 — Automated Optimization
    i("constraint-schema", "Define composable optimization constraints", "v0.9 — Automated Optimization", "Search", "P0", "Feature", "M", "High", "search", ("config-schema", "surgeon-metrics"),
      "Represent minimum quality retention, maximum delta perplexity, minimum latency gain and RAM/VRAM/disk limits.",
      "Units and baseline references are explicit.", "Multiple hard constraints compose deterministically."),
    i("objective-schema", "Define configurable multi-objective reward functions", "v0.9 — Automated Optimization", "Search", "P0", "Feature", "M", "High", "search", ("constraint-schema",),
      "Compose quality, parameter, latency, memory and disk objectives with normalization and weights.",
      "No single objective is hard-coded.", "Canonical objective serialization participates in run identity."),
    i("pareto-archive", "Maintain a persistent Pareto frontier of candidates", "v0.9 — Automated Optimization", "Search", "P1", "Feature", "L", "High", "search", ("objective-schema", "sqlite-store"),
      "Insert, dominate, query and resume candidates with missing/noisy objectives and confidence bounds.",
      "Dominance rules are documented and deterministic.", "Archive persists across restarts."),
    i("sequence-candidates", "Generate graph-valid sequences of mutations", "v0.9 — Automated Optimization", "Search", "P0", "Feature", "L", "High", "search", ("physical-plan", "candidate-dedup", "constraint-schema"),
      "Extend a model state with compatible non-conflicting plans while tracking identity remaps and cumulative costs.",
      "Invalidated IDs are never reused.", "Equivalent sequences can be deduplicated where commutativity is proven."),
    i("search-policies", "Implement greedy beam and uncertainty-aware search policies", "v0.9 — Automated Optimization", "Search", "P0", "Feature", "L", "Research", "search", ("sequence-candidates", "pareto-archive", "quant-aware-surgeon"),
      "Select sequences using predicted objectives, constraints and uncertainty under a configurable beam/evaluation budget.",
      "Policies are seeded and resumable.", "Selection reasons and predicted outcomes are stored."),
    i("keep-rollback", "Implement evaluated keep rollback and checkpoint lineage policy", "v0.9 — Automated Optimization", "Search", "P0", "Feature", "L", "High", "search", ("search-policies", "artifact-store", "mutation-transaction"),
      "Accept candidates only when measured constraints pass, otherwise restore prior lineage state and release artifacts.",
      "Every accepted checkpoint has one immutable parent and evaluation evidence.", "Rejected states cannot become search roots."),
    i("search-resume", "Resume iterative search after interruption or reboot", "v0.9 — Automated Optimization", "Search", "P0", "Infrastructure", "L", "High", "search", ("keep-rollback", "run-state-machine"),
      "Checkpoint frontier, RNG state, model lineage, budget and pending evaluations atomically.",
      "Resumed search produces the same decisions when evidence arrival order is fixed."),
    i("lora-repair", "Implement bounded LoRA repair after surgery", "v0.9 — Automated Optimization", "Optimization", "P1", "Feature", "L", "High", "surgery", ("hf-mlp-remove", "calibration-hf", "resource-budget"),
      "Train configurable low-rank adapters on a small repair set without modifying source checkpoints.",
      "Trainable parameters, steps, seed and resource use are recorded.", "Repair can be merged or retained separately."),
    i("short-finetune", "Implement short post-surgery fine-tuning repair", "v0.9 — Automated Optimization", "Optimization", "P2", "Feature", "L", "High", "surgery", ("lora-repair",),
      "Run bounded full/selected-parameter fine-tuning with early stopping and safe output lineage.",
      "Budget and overfit checks are enforced.", "Baseline/no-repair comparison is recorded."),
    i("distillation-repair", "Implement teacher-student logit distillation repair", "v0.9 — Automated Optimization", "Optimization", "P2", "Feature", "L", "High", "surgery", ("logit-metrics", "lora-repair"),
      "Use immutable baseline logits or teacher inference for bounded post-surgery distillation.",
      "Teacher/candidate tokenizer compatibility is validated.", "Temperature, loss mix and cost are recorded."),
    i("search-cli", "Implement constrained search CLI command", "v0.9 — Automated Optimization", "Foundation", "P0", "Feature", "M", "Medium", "cli", ("search-resume", "objective-schema"),
      "Start/resume search with quality, perplexity, latency, memory and parameter objectives from CLI/config.",
      "Dry-run prints constraints, budget and initial pool.", "Output identifies accepted checkpoint lineage."),
    i("iterative-study", "Evaluate automated iterative surgery and repair", "v0.9 — Automated Optimization", "Search", "P0", "Research", "L", "Research", "search", ("search-cli", "lora-repair", "q8-iterative"),
      "Run reproducible HF and native-GGUF searches toward quality-retention and latency/size goals.",
      "Compare no-repair, repair and one-shot baselines.", "Report total experiment and hardware cost."),

    # v1.0 — Release
    i("attribution", "Implement tree and linear feature attribution", "v1.0 — ModelSurgeon", "Explainability", "P1", "Feature", "M", "Medium", "explainability", ("model-registry", "quant-aware-surgeon"),
      "Produce local contributions for linear and tree predictions with feature provenance and missingness.",
      "Attributions reconcile with predictions within tolerance.", "Unsupported model types identify available fallback."),
    i("decision-summary", "Generate deterministic mutation decision summaries", "v1.0 — ModelSurgeon", "Explainability", "P1", "Feature", "M", "Low", "explainability", ("attribution", "expected-deltas"),
      "Render candidate, safe probability, top evidence, expected deltas, uncertainty and quantization context without an LLM.",
      "JSON and human text contain consistent values.", "Unknown estimates are labeled rather than invented."),
    i("report-generator", "Generate reproducible run campaign and search reports", "v1.0 — ModelSurgeon", "Explainability", "P0", "Feature", "L", "Medium", "explainability", ("decision-summary", "pareto-archive", "runtime-telemetry"),
      "Create self-contained HTML and JSON reports with configs, lineage, metrics, plots, failures and hardware.",
      "Reports link immutable IDs and redact configured paths.", "Generation is deterministic apart from declared timestamps."),
    i("calibrate-cli", "Implement calibrate CLI command", "v1.0 — ModelSurgeon", "Foundation", "P1", "Feature", "S", "Low", "cli", ("calibration-hf", "config-files"),
      "Build/reuse a calibration manifest and report tokens, revision and cache identity.",
      "Dry-run performs no dataset write.", "Interrupt preserves valid completed cache entries."),
    i("features-cli", "Implement features CLI command", "v1.0 — ModelSurgeon", "Foundation", "P1", "Feature", "M", "Low", "cli", ("instrumentation-integration", "feature-cache"),
      "Select extractor groups, enforce budgets and persist/report feature partitions.",
      "Command supports CPU and component filters.", "Output identifies every skipped extractor reason."),
    i("dataset-cli", "Implement generate-dataset CLI command", "v1.0 — ModelSurgeon", "Foundation", "P1", "Feature", "M", "Medium", "cli", ("dataset-integration",),
      "Start/resume mutation campaigns and emit validated split datasets under budgets.",
      "Progress and failure counts are available without opening the database."),
    i("report-cli", "Implement report CLI command", "v1.0 — ModelSurgeon", "Foundation", "P1", "Feature", "S", "Low", "cli", ("report-generator",),
      "Resolve a run/campaign/search ID and create human and machine-readable reports.",
      "Unknown or incomplete IDs return actionable state."),
    i("reproduce-cli", "Implement reproduce RUN_ID command", "v1.0 — ModelSurgeon", "Release", "P0", "Feature", "L", "High", "cli", ("repro-capture", "config-files", "run-state-machine"),
      "Verify revisions and environment, reconstruct resolved configuration and rerun or explain mismatches.",
      "Dry-run lists exact inputs and commands.", "Reproduced metrics link to the original with tolerance comparison."),
    i("cli-help", "Unify CLI UX progress errors and shell completion", "v1.0 — ModelSurgeon", "Release", "P1", "Documentation", "M", "Low", "cli", ("search-cli", "report-cli", "reproduce-cli"),
      "Apply consistent option names, exit codes, progress behavior, JSON mode and completion across commands.",
      "Help examples are smoke-tested.", "Non-interactive mode emits no control sequences."),
    i("performance-regression", "Add CPU RAM VRAM and GGUF streaming regression budgets", "v1.0 — ModelSurgeon", "Optimization", "P0", "Performance", "L", "High", "ci", ("scale-study", "native-gguf-proof"),
      "Track representative stage runtimes, peaks and I/O with stable fixtures and alert thresholds.",
      "PR CPU checks remain small; larger/GPU cases run separately.", "Regression baselines include hardware context."),
    i("metric-regression", "Add golden metric and schema compatibility regression suite", "v1.0 — ModelSurgeon", "Release", "P0", "Testing", "L", "High", "ci", ("report-generator", "gguf-compat-suite"),
      "Pin known model/mutation metrics, serialized schemas and migration fixtures across supported versions.",
      "Silent metric-definition changes fail tests.", "Intentional changes require version and changelog updates."),
    i("windows-wsl", "Validate Windows 11 and WSL2 consumer workflow", "v1.0 — ModelSurgeon", "Release", "P0", "Testing", "L", "High", "ci", ("iterative-study", "reproduce-cli"),
      "Run documented install, HF loop and native GGUF proof on Windows/WSL2 reference-class hardware.",
      "Path, mmap, interrupt, disk and CUDA offload behavior are validated.", "Known platform differences are documented."),
    i("security-hardening", "Harden untrusted model artifact and subprocess boundaries", "v1.0 — ModelSurgeon", "Release", "P0", "Infrastructure", "L", "High", "ci", ("checkpoint-path-safety", "llamacpp-quant-tools", "artifact-store"),
      "Threat-model remote code, GGUF parsing, path traversal, command invocation, unsafe deserialization and disk exhaustion.",
      "Fuzz/property tests cover parsers and paths.", "External commands use argument arrays and pinned executable discovery."),
    i("api-stability", "Stabilize public schemas adapter and mutation APIs", "v1.0 — ModelSurgeon", "Release", "P0", "Documentation", "L", "High", "docs", ("metric-regression", "security-hardening"),
      "Review public contracts, mark experimental surfaces, add compatibility policy and complete API reference.",
      "Every public object has documentation and type coverage.", "Breaking changes are resolved or versioned."),
    i("user-guides", "Write end-to-end HF and native GGUF user guides", "v1.0 — ModelSurgeon", "Release", "P0", "Documentation", "L", "Medium", "docs", ("windows-wsl", "cli-help", "api-stability"),
      "Document safe install, first experiment, 12 GB GPU tuning, CPU-only mode, Q4_K_M surgery, resume, reproduce and failure recovery.",
      "Commands are tested against release candidate.", "Warnings prohibit overwriting source checkpoints."),
    i("research-report", "Publish v1.0 scientific results and limitations", "v1.0 — ModelSurgeon", "Release", "P1", "Documentation", "L", "Research", "docs", ("q3-gradient", "q6-cross-family", "q7-active", "quant-loss-study", "iterative-study"),
      "Synthesize Q1–Q8, quantization findings, negative results, validity threats and hardware costs.",
      "Every claim links reproducible run IDs.", "Limitations distinguish prediction, masking and physical-surgery evidence."),
    i("release-automation", "Automate signed packages changelog and release checks", "v1.0 — ModelSurgeon", "Release", "P0", "Infrastructure", "L", "Medium", "ci", ("api-stability", "user-guides"),
      "Build sdist/wheel, verify metadata, generate changelog, attest artifacts and publish only through approval-gated workflow.",
      "Test installation in a clean Python 3.12 environment.", "Release job requires all compatibility and regression gates."),
    i("v1-release", "Cut reproducible ModelSurgeon v1.0 release", "v1.0 — ModelSurgeon", "Release", "P0", "Documentation", "M", "High", "docs", ("release-automation", "research-report", "performance-regression"),
      "Run the final audit, tag v1.0, publish artifacts/docs and archive reference experiment manifests.",
      "All P0 v1.0 issues are closed.", "CI, compatibility and consumer-hardware acceptance suites pass.", "Release notes list supported models, formats, codecs and limitations."),
]


def validate_catalog() -> None:
    """Raise when keys, dependencies, fields, or topological order are invalid."""
    seen: set[str] = set()
    milestone_names = {name for name, _ in MILESTONES}
    for spec in ISSUES:
        if spec.key in seen:
            raise ValueError(f"duplicate issue key: {spec.key}")
        if spec.milestone not in milestone_names:
            raise ValueError(f"unknown milestone for {spec.key}: {spec.milestone}")
        if spec.phase not in PHASES:
            raise ValueError(f"unknown phase for {spec.key}: {spec.phase}")
        missing = set(spec.dependencies) - seen
        if missing:
            raise ValueError(f"{spec.key} depends on missing or later keys: {sorted(missing)}")
        if not spec.acceptance or not spec.tests:
            raise ValueError(f"{spec.key} lacks acceptance criteria or tests")
        seen.add(spec.key)


validate_catalog()
