"""Prediction explanations and reports."""

from modelsurgeon.explain.attribution import (
    ATTRIBUTION_SCHEMA_VERSION,
    AttributionError,
    AttributionReport,
    AttributionResult,
    AttributionUnavailable,
    FeatureContribution,
    FeatureProvenance,
    PredictionAttribution,
    attribute_predictions,
)
from modelsurgeon.explain.decision_summary import (
    DECISION_SUMMARY_SCHEMA_VERSION,
    DecisionEvidence,
    DecisionSummaryError,
    ExpectedDeltaSummary,
    MutationDecisionSummary,
    QuantizationContext,
    generate_mutation_decision_summary,
)
from modelsurgeon.explain.explorer import (
    EXPLORER_SCHEMA_VERSION,
    ExplorerArtifact,
    ExplorerCell,
    ExplorerCellStatus,
    ExplorerError,
    generate_explorer,
    pareto_front,
    write_explorer,
)
from modelsurgeon.explain.reporting import (
    REPORT_SCHEMA_VERSION,
    GeneratedReport,
    ReportFailure,
    ReportGenerationError,
    ReportInput,
    ReportLink,
    ReportPlot,
    ReportRedaction,
    generate_report,
)

__all__ = [
    "ATTRIBUTION_SCHEMA_VERSION",
    "DECISION_SUMMARY_SCHEMA_VERSION",
    "EXPLORER_SCHEMA_VERSION",
    "REPORT_SCHEMA_VERSION",
    "AttributionError",
    "AttributionReport",
    "AttributionResult",
    "AttributionUnavailable",
    "DecisionEvidence",
    "DecisionSummaryError",
    "ExpectedDeltaSummary",
    "ExplorerArtifact",
    "ExplorerCell",
    "ExplorerCellStatus",
    "ExplorerError",
    "FeatureContribution",
    "FeatureProvenance",
    "GeneratedReport",
    "MutationDecisionSummary",
    "PredictionAttribution",
    "QuantizationContext",
    "ReportFailure",
    "ReportGenerationError",
    "ReportInput",
    "ReportLink",
    "ReportPlot",
    "ReportRedaction",
    "attribute_predictions",
    "generate_explorer",
    "generate_mutation_decision_summary",
    "generate_report",
    "pareto_front",
    "write_explorer",
]
