"""Deterministic, fail-closed clarification state machine.

Clarification is a control-plane record around :class:`IntentRecord`.  It does
not interpret free text, invent a threshold, or edit an objective contract in
place.  A typed answer is applied to one question, then the resulting intent
is compiled and policy-evaluated again.  Only that canonical policy result can
make the state executable.
"""

from __future__ import annotations

import hashlib
import json
import math
import re
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from enum import StrEnum
from typing import TYPE_CHECKING, cast

from .intent import (
    IntentField,
    IntentOutcome,
    IntentProvenance,
    IntentRecord,
    InterpretationStep,
)

if TYPE_CHECKING:
    from modelsurgeon.search.intent_policy import IntentPolicyDecision

CLARIFICATION_SCHEMA_VERSION = 1
_IDENTIFIER = re.compile(r"^[a-z][a-z0-9_.-]{0,127}$")
_MAX_ANSWER_BYTES = 64 * 1024


class ClarificationError(ValueError):
    """Raised when a clarification record or transition is unsafe."""


class ClarificationStatus(StrEnum):
    INCOMPLETE = "incomplete"
    AMBIGUOUS = "ambiguous"
    CONTRADICTORY = "contradictory"
    EXECUTABLE = "executable"
    REPEATED = "repeated"
    CANCELLED = "cancelled"
    UNSUPPORTED = "unsupported"


class ClarificationTransitionKind(StrEnum):
    STARTED = "started"
    ANSWER_ACCEPTED = "answer_accepted"
    ANSWER_REPEATED = "answer_repeated"
    ANSWER_UNSUPPORTED = "answer_unsupported"
    ANSWER_CONTRADICTORY = "answer_contradictory"
    CANCELLED = "cancelled"


def _canonical(value: object) -> str:
    try:
        return json.dumps(
            value,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
            allow_nan=False,
        )
    except (TypeError, ValueError) as error:
        raise ClarificationError("clarification value is not canonical JSON") from error


def _digest(value: object) -> str:
    return "sha256:" + hashlib.sha256(_canonical(value).encode("utf-8")).hexdigest()


def _identifier(value: object, label: str) -> str:
    if not isinstance(value, str) or _IDENTIFIER.fullmatch(value) is None:
        raise ClarificationError(f"{label} must be a canonical identifier")
    return value


def _text(value: object, label: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ClarificationError(f"{label} must be non-empty text")
    return value


def _sorted_unique(values: tuple[str, ...], label: str) -> None:
    if values != tuple(sorted(set(values))):
        raise ClarificationError(f"{label} must be sorted and unique")


def _object(value: object, label: str) -> dict[str, object]:
    if not isinstance(value, Mapping) or not all(isinstance(key, str) for key in value):
        raise ClarificationError(f"{label} must be a JSON object")
    return dict(value)


@dataclass(frozen=True, slots=True)
class ClarificationQuestion:
    """One necessary, typed question generated by canonical policy."""

    question_id: str
    field_id: str
    category: str
    prompt: str
    alternatives: tuple[str, ...] = ()
    required: bool = True
    source_span_ids: tuple[str, ...] = ()
    diagnostic_codes: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        _identifier(self.question_id, "clarification question ID")
        _identifier(self.field_id, "clarification field ID")
        _identifier(self.category, "clarification category")
        _text(self.prompt, "clarification prompt")
        _sorted_unique(self.alternatives, "clarification alternatives")
        _sorted_unique(self.source_span_ids, "clarification source spans")
        _sorted_unique(self.diagnostic_codes, "clarification diagnostic codes")

    def to_record(self) -> dict[str, object]:
        return {
            "question_id": self.question_id,
            "field_id": self.field_id,
            "category": self.category,
            "prompt": self.prompt,
            "alternatives": list(self.alternatives),
            "required": self.required,
            "source_span_ids": list(self.source_span_ids),
            "diagnostic_codes": list(self.diagnostic_codes),
        }


@dataclass(frozen=True, slots=True)
class ClarificationAnswer:
    """A bounded typed answer; raw provider text is never an answer record."""

    question_id: str
    value: object

    def __post_init__(self) -> None:
        _identifier(self.question_id, "clarification answer question ID")
        encoded = _canonical(self.value)
        if len(encoded.encode("utf-8")) > _MAX_ANSWER_BYTES:
            raise ClarificationError("clarification answer exceeds the size limit")

    @property
    def answer_digest(self) -> str:
        return _digest({"question_id": self.question_id, "value": self.value})

    def to_record(self) -> dict[str, object]:
        return {
            "question_id": self.question_id,
            "value": self.value,
            "answer_digest": self.answer_digest,
        }


@dataclass(frozen=True, slots=True)
class ClarificationTransition:
    """One deterministic state transition, including rejected attempts."""

    revision: int
    kind: ClarificationTransitionKind
    answer_digest: str | None
    status: ClarificationStatus
    detail: str

    def __post_init__(self) -> None:
        if isinstance(self.revision, bool) or self.revision <= 0:
            raise ClarificationError("clarification transition revision must be positive")
        if self.answer_digest is not None and not re.fullmatch(
            r"sha256:[0-9a-f]{64}", self.answer_digest
        ):
            raise ClarificationError("clarification answer digest is invalid")
        _text(self.detail, "clarification transition detail")

    def to_record(self) -> dict[str, object]:
        return {
            "revision": self.revision,
            "kind": self.kind.value,
            "answer_digest": self.answer_digest,
            "status": self.status.value,
            "detail": self.detail,
        }


@dataclass(frozen=True, slots=True)
class ClarificationState:
    """Canonical resumable state for one intent clarification exchange."""

    root_intent: IntentRecord
    intent: IntentRecord
    policy: IntentPolicyDecision
    status: ClarificationStatus
    questions: tuple[ClarificationQuestion, ...]
    answers: tuple[ClarificationAnswer, ...]
    transitions: tuple[ClarificationTransition, ...]
    high_confidence: float = 0.9
    medium_confidence: float = 0.7
    schema_version: int = CLARIFICATION_SCHEMA_VERSION

    def __post_init__(self) -> None:
        if self.schema_version != CLARIFICATION_SCHEMA_VERSION:
            raise ClarificationError("unsupported clarification schema version")
        if self.root_intent.original_request != self.intent.original_request:
            raise ClarificationError("clarification cannot change the original request")
        if self.policy.intent_id != self.intent.intent_id:
            raise ClarificationError("clarification policy belongs to another intent")
        if not 0 <= self.medium_confidence <= self.high_confidence <= 1:
            raise ClarificationError("clarification confidence thresholds are invalid")
        if tuple(sorted(self.questions, key=lambda item: item.question_id)) != self.questions:
            raise ClarificationError("clarification questions must be canonical")
        if tuple(item.question_id for item in self.questions) != tuple(
            sorted({item.question_id for item in self.questions})
        ):
            raise ClarificationError("clarification question IDs must be unique")
        if (
            not self.transitions
            or self.transitions[0].kind is not ClarificationTransitionKind.STARTED
        ):
            raise ClarificationError("clarification state requires a started transition")
        if tuple(item.revision for item in self.transitions) != tuple(
            range(1, len(self.transitions) + 1)
        ):
            raise ClarificationError("clarification transitions must be contiguous")

    @property
    def revision(self) -> int:
        return len(self.transitions)

    @property
    def state_id(self) -> str:
        return (
            "clarification_"
            + hashlib.sha256(
                self.canonical_json(include_identity=False).encode("utf-8")
            ).hexdigest()
        )

    @property
    def executable(self) -> bool:
        return self.status is ClarificationStatus.EXECUTABLE and self.policy.executable

    def to_record(self, *, include_identity: bool = True) -> dict[str, object]:
        record: dict[str, object] = {
            "schema_version": self.schema_version,
            "root_intent": self.root_intent.to_record(),
            "intent": self.intent.to_record(),
            "policy": self.policy.to_record(),
            "status": self.status.value,
            "questions": [item.to_record() for item in self.questions],
            "answers": [item.to_record() for item in self.answers],
            "transitions": [item.to_record() for item in self.transitions],
            "policy_thresholds": {
                "high": self.high_confidence,
                "medium": self.medium_confidence,
            },
        }
        if include_identity:
            record["state_id"] = self.state_id
        return record

    def canonical_json(self, *, include_identity: bool = True) -> str:
        return _canonical(self.to_record(include_identity=include_identity))

    @classmethod
    def from_json(cls, payload: str) -> ClarificationState:
        try:
            root = _object(json.loads(payload), "clarification state")
        except json.JSONDecodeError as error:
            raise ClarificationError("clarification state is not valid JSON") from error
        expected = {
            "schema_version",
            "root_intent",
            "intent",
            "policy",
            "status",
            "questions",
            "answers",
            "transitions",
            "policy_thresholds",
            "state_id",
        }
        if set(root) != expected:
            raise ClarificationError("clarification state has missing or unknown fields")
        if root["schema_version"] != CLARIFICATION_SCHEMA_VERSION:
            raise ClarificationError("unsupported clarification schema version")
        thresholds = _object(root["policy_thresholds"], "clarification policy thresholds")
        high = thresholds.get("high")
        medium = thresholds.get("medium")
        if (
            isinstance(high, bool)
            or not isinstance(high, (int, float))
            or isinstance(medium, bool)
            or not isinstance(medium, (int, float))
            or not math.isfinite(float(high))
            or not math.isfinite(float(medium))
        ):
            raise ClarificationError("clarification policy thresholds are invalid")
        root_intent = IntentRecord.from_json(_canonical(root["root_intent"]))
        intent = IntentRecord.from_json(_canonical(root["intent"]))
        from modelsurgeon.search.intent_policy import evaluate_intent_policy

        policy = evaluate_intent_policy(
            intent, high_confidence=float(high), medium_confidence=float(medium)
        )
        if policy.to_record() != root["policy"]:
            raise ClarificationError("clarification policy does not match canonical intent")
        questions = tuple(_question(item) for item in _array(root["questions"], "questions"))
        answers = tuple(_answer(item) for item in _array(root["answers"], "answers"))
        transitions = tuple(
            _transition(item) for item in _array(root["transitions"], "transitions")
        )
        try:
            status = ClarificationStatus(cast(str, root["status"]))
        except ValueError as error:
            raise ClarificationError("clarification status is unknown") from error
        result = cls(
            root_intent,
            intent,
            policy,
            status,
            questions,
            answers,
            transitions,
            float(high),
            float(medium),
        )
        if root["state_id"] != result.state_id:
            raise ClarificationError("clarification state ID does not match canonical state")
        return result


class ClarificationMachine:
    """Apply typed clarification answers with deterministic replay semantics."""

    def __init__(self, *, high_confidence: float = 0.9, medium_confidence: float = 0.7):
        if not 0 <= medium_confidence <= high_confidence <= 1:
            raise ClarificationError("confidence thresholds must satisfy 0 <= medium <= high <= 1")
        self.high_confidence = float(high_confidence)
        self.medium_confidence = float(medium_confidence)

    def start(
        self, intent: IntentRecord, policy: IntentPolicyDecision | None = None
    ) -> ClarificationState:
        if not isinstance(intent, IntentRecord):
            raise ClarificationError("clarification requires an IntentRecord")
        if policy is None:
            from modelsurgeon.search.intent_policy import evaluate_intent_policy

            policy = evaluate_intent_policy(
                intent,
                high_confidence=self.high_confidence,
                medium_confidence=self.medium_confidence,
            )
        if policy.intent_id != intent.intent_id:
            raise ClarificationError("clarification policy belongs to another intent")
        status = _status_for_policy(policy)
        questions = (
            _necessary_questions(intent, policy)
            if status
            in {
                ClarificationStatus.INCOMPLETE,
                ClarificationStatus.AMBIGUOUS,
            }
            else ()
        )
        return ClarificationState(
            intent,
            intent,
            policy,
            status,
            questions,
            (),
            (
                ClarificationTransition(
                    1, ClarificationTransitionKind.STARTED, None, status, "clarification evaluated"
                ),
            ),
            self.high_confidence,
            self.medium_confidence,
        )

    def answer(self, state: ClarificationState, answer: ClarificationAnswer) -> ClarificationState:
        if not isinstance(state, ClarificationState) or not isinstance(answer, ClarificationAnswer):
            raise ClarificationError("clarification answer requires typed state and answer")
        if state.status is ClarificationStatus.CANCELLED:
            raise ClarificationError("cancelled clarification cannot accept answers")
        if state.status is ClarificationStatus.EXECUTABLE:
            raise ClarificationError("executable clarification cannot accept answers")
        question = next(
            (item for item in state.questions if item.question_id == answer.question_id), None
        )
        if question is None:
            return self._attempt_result(
                state,
                answer,
                ClarificationTransitionKind.ANSWER_UNSUPPORTED,
                ClarificationStatus.UNSUPPORTED,
                "answer refers to a question that is not currently necessary",
            )
        if any(item.answer_digest == answer.answer_digest for item in state.answers):
            return self._attempt_result(
                state,
                answer,
                ClarificationTransitionKind.ANSWER_REPEATED,
                ClarificationStatus.REPEATED,
                "answer was already applied",
            )
        try:
            updated_intent = self._apply_answer(state, question, answer)
        except _UnsupportedAnswer as error:
            return self._attempt_result(
                state,
                answer,
                ClarificationTransitionKind.ANSWER_UNSUPPORTED,
                ClarificationStatus.UNSUPPORTED,
                str(error),
            )
        except _ContradictoryAnswer as error:
            return self._attempt_result(
                state,
                answer,
                ClarificationTransitionKind.ANSWER_CONTRADICTORY,
                ClarificationStatus.CONTRADICTORY,
                str(error),
                intent=state.intent,
            )

        from modelsurgeon.search.intent_policy import evaluate_intent_policy

        policy = evaluate_intent_policy(
            updated_intent,
            high_confidence=self.high_confidence,
            medium_confidence=self.medium_confidence,
        )
        status = _status_for_policy(policy)
        questions = (
            _necessary_questions(updated_intent, policy)
            if status
            in {
                ClarificationStatus.INCOMPLETE,
                ClarificationStatus.AMBIGUOUS,
            }
            else ()
        )
        answers = (*state.answers, answer)
        kind = (
            ClarificationTransitionKind.ANSWER_CONTRADICTORY
            if status is ClarificationStatus.CONTRADICTORY
            else ClarificationTransitionKind.ANSWER_ACCEPTED
        )
        transition = ClarificationTransition(
            state.revision + 1,
            kind,
            answer.answer_digest,
            status,
            "answer applied and canonical policy re-evaluated",
        )
        return ClarificationState(
            state.root_intent,
            updated_intent,
            policy,
            status,
            questions,
            answers,
            (*state.transitions, transition),
            self.high_confidence,
            self.medium_confidence,
        )

    def cancel(self, state: ClarificationState) -> ClarificationState:
        if not isinstance(state, ClarificationState):
            raise ClarificationError("clarification cancellation requires typed state")
        if state.status is ClarificationStatus.CANCELLED:
            return state
        transition = ClarificationTransition(
            state.revision + 1,
            ClarificationTransitionKind.CANCELLED,
            None,
            ClarificationStatus.CANCELLED,
            "clarification cancelled by the user",
        )
        return ClarificationState(
            state.root_intent,
            state.intent,
            state.policy,
            ClarificationStatus.CANCELLED,
            (),
            state.answers,
            (*state.transitions, transition),
            self.high_confidence,
            self.medium_confidence,
        )

    def replay(
        self, intent: IntentRecord, answers: Sequence[ClarificationAnswer]
    ) -> ClarificationState:
        state = self.start(intent)
        for answer in answers:
            state = self.answer(state, answer)
        return state

    def _attempt_result(
        self,
        state: ClarificationState,
        answer: ClarificationAnswer,
        kind: ClarificationTransitionKind,
        status: ClarificationStatus,
        detail: str,
        *,
        intent: IntentRecord | None = None,
    ) -> ClarificationState:
        transition = ClarificationTransition(
            state.revision + 1, kind, answer.answer_digest, status, detail
        )
        return ClarificationState(
            state.root_intent,
            state.intent if intent is None else intent,
            state.policy,
            status,
            state.questions,
            (*state.answers, answer),
            (*state.transitions, transition),
            self.high_confidence,
            self.medium_confidence,
        )

    def _apply_answer(
        self,
        state: ClarificationState,
        question: ClarificationQuestion,
        answer: ClarificationAnswer,
    ) -> IntentRecord:
        fields = {item.field_id: item for item in state.intent.fields}
        existing = fields.get(question.field_id)
        value = answer.value
        if question.alternatives and isinstance(value, str) and value not in question.alternatives:
            raise _UnsupportedAnswer("answer is not one of the declared alternatives")
        if question.category in {"missing-hard-constraint", "missing-soft-objective"}:
            value = _declaration(
                value,
                "hard_constraint" if question.category.endswith("constraint") else "soft_objective",
            )
        elif existing is None:
            raise _UnsupportedAnswer("answer does not provide the required typed declaration")
        elif isinstance(value, Mapping):
            value = dict(value)
        elif question.alternatives:
            value = existing.value
        else:
            raise _UnsupportedAnswer("answer must be a typed JSON object")
        if existing is not None:
            old_kind = _kind(existing.value)
            new_kind = _kind(value)
            if old_kind == "hard_constraint" and new_kind != "hard_constraint":
                raise _ContradictoryAnswer("answer cannot remove an existing hard constraint")
            fields[question.field_id] = IntentField(
                existing.field_id,
                value,
                existing.unit
                if not isinstance(value, Mapping)
                else _optional_text(value.get("unit")),
                1.0,
                existing.source_span_ids,
                existing.required,
            )
        else:
            if not isinstance(value, Mapping):
                raise _UnsupportedAnswer("new declarations must be typed objects")
            metric = value.get("metric")
            if not isinstance(metric, str) or _IDENTIFIER.fullmatch(metric) is None:
                raise _UnsupportedAnswer("answer declaration metric is not canonical")
            field_id = (
                "constraint." if question.category == "missing-hard-constraint" else "objective."
            ) + metric
            if field_id in fields:
                raise _UnsupportedAnswer("answer declaration duplicates an existing field")
            fields[field_id] = IntentField(
                field_id,
                value,
                _optional_text(value.get("unit")),
                1.0,
                (),
                question.category == "missing-hard-constraint",
            )
        ambiguities = tuple(
            item for item in state.intent.ambiguities if item.field_id != question.field_id
        )
        answer_ref = "clarification-answer:" + answer.answer_digest
        provenance = IntentProvenance(
            state.intent.provenance.source_revision,
            state.intent.provenance.provider_id,
            state.intent.provenance.provider_revision,
            state.intent.provenance.tool_revision,
            tuple(sorted(set((*state.intent.provenance.evidence_refs, answer_ref)))),
        )
        step_id = "step-clarification-" + answer.answer_digest[len("sha256:") : 24]
        answered_field_id = question.field_id
        if existing is None:
            answered_field_id = next(
                item.field_id for item in fields.values() if item not in state.intent.fields
            )
        steps = (
            *state.intent.interpretation_steps,
            InterpretationStep(
                step_id,
                "clarification_answer",
                (),
                (answered_field_id,),
                1.0,
                (answer_ref,),
            ),
        )
        try:
            spec = _spec_from_fields(tuple(fields.values()))
        except _UnsupportedAnswer:
            outcome = IntentOutcome.UNSUPPORTED
            spec = None
        except _ContradictoryAnswer:
            outcome = IntentOutcome.REFUSED
            spec = None
        else:
            outcome = (
                IntentOutcome.EXECUTABLE
                if spec is not None
                else IntentOutcome.CLARIFICATION_REQUIRED
            )
        return IntentRecord(
            state.intent.original_request,
            state.intent.source_spans,
            tuple(sorted(fields.values(), key=lambda item: item.field_id)),
            ambiguities,
            tuple(sorted(steps, key=lambda item: item.step_id)),
            provenance,
            outcome,
            ("clarification answer applied",),
            spec,
        )


class _UnsupportedAnswer(ValueError):
    pass


class _ContradictoryAnswer(ValueError):
    pass


def _kind(value: object) -> str | None:
    if not isinstance(value, Mapping):
        return None
    raw = value.get("kind", value.get("type", value.get("declaration")))
    if not isinstance(raw, str):
        return None
    return {
        "constraint": "hard_constraint",
        "hard_constraint": "hard_constraint",
        "hard-constraint": "hard_constraint",
        "objective": "soft_objective",
        "soft_objective": "soft_objective",
        "soft-objective": "soft_objective",
        "preference": "soft_objective",
    }.get(raw)


def _optional_text(value: object) -> str | None:
    return value if isinstance(value, str) else None


def _declaration(value: object, kind: str) -> object:
    if not isinstance(value, Mapping):
        raise _UnsupportedAnswer("declaration answer must be a JSON object")
    result = dict(value)
    supplied = result.get("kind", result.get("type", result.get("declaration")))
    if supplied is not None and _kind(result) != kind:
        raise _ContradictoryAnswer("answer declaration kind contradicts the necessary question")
    required = (
        {"metric", "direction", "threshold", "unit"}
        if kind == "hard_constraint"
        else {"metric", "direction", "unit"}
    )
    if not required.issubset(result):
        raise _UnsupportedAnswer("answer declaration is missing required schema fields")
    result["kind"] = kind
    return result


def _spec_from_fields(fields: tuple[IntentField, ...]) -> dict[str, object] | None:
    from modelsurgeon.search.intent_compiler import _hard_constraint, _parse_field, _soft_objective
    from modelsurgeon.search.objective_contract import ObjectiveContract

    constraints = []
    objectives = []
    for field in fields:
        parsed = _parse_field(field.field_id, field.value, field.unit)
        if parsed is None:
            raise _UnsupportedAnswer("answer leaves an unsupported typed field")
        kind, payload = parsed
        try:
            if kind == "hard_constraint":
                constraints.append(_hard_constraint(payload))
            else:
                objectives.append(_soft_objective(payload))
        except Exception as error:
            raise _ContradictoryAnswer("answer does not satisfy the objective schema") from error
    if not constraints or not objectives:
        return None
    try:
        return ObjectiveContract(tuple(constraints), tuple(objectives)).to_record()
    except Exception as error:
        raise _ContradictoryAnswer(
            "answer produces an invalid or contradictory objective"
        ) from error


def _status_for_policy(policy: IntentPolicyDecision) -> ClarificationStatus:
    if policy.outcome is IntentOutcome.EXECUTABLE:
        return ClarificationStatus.EXECUTABLE
    if policy.outcome is IntentOutcome.REFUSED:
        return ClarificationStatus.CONTRADICTORY
    if policy.outcome is IntentOutcome.UNSUPPORTED:
        return ClarificationStatus.UNSUPPORTED
    if any(
        item.category.value in {"vague", "conflicting", "unresolved"}
        for item in policy.ambiguities
        if item.required
    ):
        return ClarificationStatus.AMBIGUOUS
    return ClarificationStatus.INCOMPLETE


def _question(
    value: object,
) -> ClarificationQuestion:
    record = _object(value, "clarification question")
    return ClarificationQuestion(
        _identifier(record["question_id"], "question ID"),
        _identifier(record["field_id"], "field ID"),
        _identifier(record["category"], "question category"),
        _text(record["prompt"], "question prompt"),
        tuple(
            _text(item, "alternative") for item in _array(record["alternatives"], "alternatives")
        ),
        bool(record["required"]),
        tuple(
            _text(item, "source span ID")
            for item in _array(record["source_span_ids"], "source spans")
        ),
        tuple(
            _text(item, "diagnostic code")
            for item in _array(record["diagnostic_codes"], "diagnostic codes")
        ),
    )


def _answer(value: object) -> ClarificationAnswer:
    record = _object(value, "clarification answer")
    answer = ClarificationAnswer(_identifier(record["question_id"], "question ID"), record["value"])
    if record.get("answer_digest") != answer.answer_digest:
        raise ClarificationError("clarification answer digest does not match its value")
    return answer


def _transition(value: object) -> ClarificationTransition:
    record = _object(value, "clarification transition")
    try:
        kind = ClarificationTransitionKind(cast(str, record["kind"]))
        status = ClarificationStatus(cast(str, record["status"]))
    except ValueError as error:
        raise ClarificationError("clarification transition enum is unknown") from error
    return ClarificationTransition(
        cast(int, record["revision"]),
        kind,
        cast(str | None, record["answer_digest"]),
        status,
        _text(record["detail"], "transition detail"),
    )


def _array(value: object, label: str) -> list[object]:
    if not isinstance(value, list):
        raise ClarificationError(f"{label} must be an array")
    return value


def _necessary_questions(
    intent: IntentRecord, policy: IntentPolicyDecision
) -> tuple[ClarificationQuestion, ...]:
    """Generate only questions that correspond to an executable policy gap."""

    candidates: list[tuple[str, str, str, tuple[str, ...], tuple[str, ...], str]] = []
    for ambiguity in policy.ambiguities:
        if not ambiguity.required:
            continue
        if ambiguity.category.value in {"contradictory", "unsupported"}:
            continue
        prompt = (
            f"Resolve {ambiguity.field_id}: choose one of "
            + ", ".join(ambiguity.alternatives)
            + "."
        )
        candidates.append(
            (
                ambiguity.field_id,
                ambiguity.category.value,
                prompt,
                ambiguity.alternatives,
                ambiguity.source_span_ids,
                "required-ambiguity",
            )
        )
    for diagnostic in policy.diagnostics:
        category: str | None = None
        field_id = diagnostic.field_id
        prompt = diagnostic.message
        alternatives: tuple[str, ...] = ()
        if diagnostic.code == "missing-hard-constraint":
            category = "missing-hard-constraint"
            field_id = "clarification.hard-constraint"
            prompt = (
                "Provide the required hard constraint as metric, direction, threshold, and unit."
            )
        elif diagnostic.code == "missing-soft-objective":
            category = "missing-soft-objective"
            field_id = "clarification.soft-objective"
            prompt = "Provide the soft objective as metric, direction, and unit."
        elif diagnostic.code == "hard-constraint-incomplete":
            category = "missing-hard-constraint"
            field_id = "clarification.hard-constraint"
            prompt = (
                "Provide at least one hard constraint as metric, direction, threshold, and unit."
            )
        elif diagnostic.code == "low-confidence-required-field" and field_id is not None:
            category = "low-confidence"
            prompt = f"Confirm or correct the typed value for required field {field_id}."
        elif diagnostic.code == "conflicting-soft-objectives":
            category = "conflicting-soft-objective"
            field_id = field_id or "clarification.soft-objective"
            prompt = (
                "Choose one soft objective; multiple preferences for the same metric "
                "are not executable."
            )
        if category is not None and field_id is not None:
            candidates.append(
                (
                    field_id,
                    category,
                    prompt,
                    alternatives,
                    diagnostic.source_span_ids,
                    diagnostic.code,
                )
            )
    merged: dict[tuple[str, str], tuple[str, str, str, set[str], set[str]]] = {}
    for field_id, category, prompt, alternatives, spans, _code in candidates:
        key = (field_id, category)
        current = merged.get(key)
        if current is None:
            merged[key] = (field_id, category, prompt, set(alternatives), set(spans))
        else:
            current[3].update(alternatives)
            current[4].update(spans)
    result: list[ClarificationQuestion] = []
    for field_id, category, prompt, alternative_values, span_values in sorted(merged.values()):
        codes = tuple(
            sorted(
                diagnostic.code
                for diagnostic in policy.diagnostics
                if diagnostic.field_id == field_id
                or category.startswith(diagnostic.code.replace("_", "-"))
            )
        )
        identity = {
            "intent_id": intent.intent_id,
            "field_id": field_id,
            "category": category,
            "prompt": prompt,
            "alternatives": sorted(alternative_values),
            "source_span_ids": sorted(span_values),
            "diagnostic_codes": codes,
        }
        question_id = "clarification_question_" + _digest(identity)[len("sha256:") :]
        result.append(
            ClarificationQuestion(
                question_id,
                field_id,
                category,
                prompt,
                tuple(sorted(alternative_values)),
                True,
                tuple(sorted(span_values)),
                codes,
            )
        )
    return tuple(sorted(result, key=lambda item: item.question_id))


def build_clarification_state(
    intent: IntentRecord,
    policy: IntentPolicyDecision | None = None,
    *,
    high_confidence: float = 0.9,
    medium_confidence: float = 0.7,
) -> ClarificationState:
    """Build the canonical clarification state for an already interpreted intent."""

    return ClarificationMachine(
        high_confidence=high_confidence, medium_confidence=medium_confidence
    ).start(intent, policy)


def apply_clarification_answer(
    state: ClarificationState, answer: ClarificationAnswer
) -> ClarificationState:
    """Apply one answer using the thresholds retained by the state."""

    return ClarificationMachine(
        high_confidence=state.high_confidence, medium_confidence=state.medium_confidence
    ).answer(state, answer)


def replay_clarification(
    intent: IntentRecord,
    answers: Sequence[ClarificationAnswer],
    *,
    high_confidence: float = 0.9,
    medium_confidence: float = 0.7,
) -> ClarificationState:
    """Replay the same typed answers from the canonical root intent."""

    return ClarificationMachine(
        high_confidence=high_confidence, medium_confidence=medium_confidence
    ).replay(intent, answers)


__all__ = [
    "CLARIFICATION_SCHEMA_VERSION",
    "ClarificationAnswer",
    "ClarificationError",
    "ClarificationMachine",
    "ClarificationQuestion",
    "ClarificationState",
    "ClarificationStatus",
    "ClarificationTransition",
    "ClarificationTransitionKind",
    "apply_clarification_answer",
    "build_clarification_state",
    "replay_clarification",
]
